<?php
$iRank = 1;
$sRankingHtml = '';
$iBeforeCnt = 0;
$iSumCnt = 0;
foreach ($this->aMagicList as $val) {
    $sUrl = "/card/detail/{$val['card_id']}/";
    $sDeckInfoUrl = $this->url(array('controller' => 'deck', 'action' => 'list')) . "/{$val['card_id']}/";
    $sGameInfoUrl = $this->url(array('action' => 'fields')) . "/{$val['card_id']}/";
    $sDetailLink ="<a href='{$sUrl}' target='_blank' class='blank_link'>{$val['card_name']}</a>";
    $sImg = "<img src='/images/card/card.jpg' original-src='/images/card/{$val['image_file_name']}' />";
    if ($val['cnt'] != $iBeforeCnt) {
        if ($iRank <= 10) {
            $sRankImg = "<img src='/images/dot.png' original-src='/images/ranking/crown{$iRank}.png' />";
        } else {
            $sRankImg = "<div>{$iRank}</div>";
        }
    }

    $sRankingHtml .= <<<_eos_
    <div class="ranking_row clearfix">
        <div class="rank_num">
            {$sRankImg}
        </div>
        <div class="card_img">
            {$sImg}
        </div>
        <div class="card_summary">
            {$sDetailLink}<br />
            <span class="b">{$val['cnt']}回</span>
        </div>
        <div class="detail_link">
            <span><a href="{$sGameInfoUrl}" target="_blank" class="blank_link">{$val['card_name']}の使われた対戦</a></span><br />
            <span class="deck num summary"><a href="{$sDeckInfoUrl}" target="_blank" class="blank_link">{$val['card_name']}の搭載デッキ一覧</a></span>
        </div>
    </div>

_eos_;
    $iRank++;
    $iBeforeCnt =  $val['cnt'];
    $iSumCnt    += $val['cnt'];
}
$sRankingHtml .= '<div class="ranking_row"></div>';
?>
<div id="magic_ranking" class="ranking_wrapper">
    <h1>マジック使用回数　ランキング</h1>
    <div class="description">
        マジックカードの使用回数ランキングです。<br />
        現在までの累計で、<strong><?php echo $iSumCnt; ?>回</strong>マジックが使用されています。<br />
        なお、マスターの特技は集計対象外です。
    </div>
    <?php echo $sRankingHtml; ?>
</div>
