<?php
$iRank = 1;
$sRankingHtml = '';
$iBeforeCnt = 0;
$iSumCnt = 0;
foreach ($this->aDeckCardList as $val) {
    $sUrl = "/card/detail/{$val['card_id']}/";
    $sDetailLink ="<a href='{$sUrl}' target='_blank' class='blank_link'>{$val['card_name']}</a>";
    $sImg = "<img src='/images/card/card.jpg' original-src='/images/card/{$val['image_file_name']}' />";
    if ($val['cnt'] != $iBeforeCnt) {
        if ($iRank <= 10) {
            $sRankImg = "<img src='/images/dot.png' original-src='/images/ranking/crown{$iRank}.png' />";
        } else {
            $sRankImg = "<div>{$iRank}</div>";
        }
    }

    $sRankingHtml .= <<<_eos_
    <div class="ranking_row clearfix">
        <div class="rank_num">
            {$sRankImg}
        </div>
        <div class="card_img">
            {$sImg}
        </div>
        <div class="card_summary">
            {$sDetailLink}<br />
            <strong>{$val['cnt']}枚</strong>
            ({$val['decks']}デッキにて採用)
        </div>
    </div>

_eos_;
    $iRank++;
    $iBeforeCnt = $val['cnt'];
    $iSumCnt    += $val['cnt'];
}
$sRankingHtml .= '<div class="ranking_row"></div>';
?>
<div id="finisher_ranking" class="ranking_frame">
<div class="description">
    デッキに積まれたカードの枚数ランキングです。<br />
    現在、<strong><?php echo $this->iDeck; ?>個</strong>のデッキが登録されています。<br />
    未だ積まれていないカードは一覧に載っていません。また、マスターも集計対象外です。
</div>
<?php echo $sRankingHtml; ?>
</div>
