<?php
$aUserInfo = Common::checkLogin();
$deckIdHtml = '';
if (isset($this->input_deck_id) && $this->input_deck_id != '') {
    $deckIdHtml = <<<_eos_
    <input type="hidden" name="input_deck_id" value="{$this->input_deck_id}" />

_eos_;
}
$aDeckCardImages = array(
    'front' => '',
    'back'  => '',
    'magic' => '',
    'super' => '',
);
if (isset($this->aDeckInfo['cards']) && is_array($this->aDeckInfo['cards'])) {
    foreach ($this->aDeckInfo['cards'] as $val) {
        $aDeckCardImages[$val['cate']] .= <<<_eos_
<img src="/images/card/card.jpg" original-src="/images/card/{$val['image_file_name']}" cate="{$val['cate']}" cardid="{$val['card_id']}" rare="{$val['rare']}" />

_eos_;
    }
}

$sMasterImages = '';
$sMasterCatalog = '';
$sDeckName = '';
$sCardCatalog = '';

if (isset($this->aDeckInfo['deck_name'])) {
    $sDeckName = $this->escape($this->aDeckInfo['deck_name']);
}
foreach ($this->card_list as $val) {
    foreach ($val as $k => $v) {
        $val[$k] = htmlspecialchars($v, ENT_QUOTES);
    }
    if ($val['category'] == 'master') {
        $sMasterImages .= <<<_eos_
                <div cardid="{$val['card_id']}">
                    <img src="/images/card/card.jpg" original-src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}" cardid="{$val['card_id']}" rare="{$val['rare']}" />
                </div>

_eos_;
        if (isset ($this->aDeckInfo['master_card_id']) && $val['card_id'] == $this->aDeckInfo['master_card_id']) {
            $selected = ' selected';
        } else {
            $selected = '';
        }
        $sMasterCatalog .= <<<_eos_
                <option value="{$val['card_id']}"{$selected}>{$val['card_name']}</option>

_eos_;
    } else {
        if (isset($val['proposer']) && $val['proposer'] != '') {
            $val['proposer'] = 'Arranged';
        }
        $sDetailHtml = '';
        if (isset($val['monster_id']) && $val['monster_id'] != '') {
            $val['monster_id'] = explode(',', preg_replace('/[{}]/', '', $val['monster_id']));
            foreach ($val['monster_id'] as $vmon) {
                $sDetailHtml .= "<div monster_id='{$vmon}'>&nbsp;</div>";
            }
        } else if (isset($val['magic_id']) && $val['magic_id'] != '') {
            $val['magic_id'] = explode(',', preg_replace('/[{}]/', '', $val['magic_id']));
            foreach ($val['magic_id'] as $vmon) {
                $sDetailHtml .= "<div magic_id='{$vmon}'>&nbsp;</div>";
            }
        }
        $sCardCatalog .= <<<_eos_
    <div class="catalog {$val['category']}">
        <img
            alt="{$val['card_name']}"
            cardid="{$val['card_id']}"
            rare="{$val['rare']}"
            proposer="{$val['proposer']}"
            original-src="/images/card/{$val['image_file_name']}"
            src="/images/card/card.jpg"
        />
        <div class="card_info summary">
            ★{$val['rare']}<br />
            {$val['card_name']}
        </div>
        <div class="card_info detail" cardid="{$val['card_id']}">
            {$sDetailHtml}
        </div>
    </div>

_eos_;
    }
}
$sCardCatalog .= '<div class="line_head" style="clear:both;width:0;height:0;">&nbsp;</div>';
$sOpenFlgChecked = ' checked="checked" ';
if (isset($this->input_deck_id, $this->aDeckInfo) && !empty($this->aDeckInfo) && $this->aDeckInfo['open_flg'] == false) {
    $sOpenFlgChecked = '';
}

$sSecretDeckHtml = '';
if ($aUserInfo) {
    $sSecretDeckHtml = <<<_eos_
            <div class="open_switch">
                <input type="checkbox" name="open_flg" {$sOpenFlgChecked} />デッキを公開する
            </div>

_eos_;
}
?>
<div id="deck_frame">
    <form name="deck_edit_form" method="post">
        <?php echo $deckIdHtml; ?>
        <div class="deck_header clearfix">
            <div class="master_image">
                <?php echo $sMasterImages; ?>
            </div>
            <div class="deck_summary">
                <div class="title">
                    デッキ名：<br />
                    <input type="text" name="deck_name" value="<?php echo $sDeckName; ?>" />
                </div>
            </div>
            <?php echo $sSecretDeckHtml; ?>
        </div>
        <div class="master_select">
            <select name="master">
                <?php echo $sMasterCatalog; ?>
            </select>
            <a class="blank_link" href="/card/detail/1002/" target="_blank">マスター詳細</a>
        </div>
        <div class="card_list_in_deck">
            <div class="deck">
                デッキ枚数:<span id="deck_cards_num">0</span>枚&nbsp;
                合計Rare:<span id="deck_sum_rare">★0</span>&nbsp;
                最大Rare:<span id="deck_max_rare">★0</span>
            </div>
            <div class="front">前衛モンスター枚数:<span id="front_cards_num">0</span>枚</div>
            <div class="front card_image_frame">
                <?php echo $aDeckCardImages['front']; ?>
            </div>
            <div class="back">後衛モンスター枚数:<span id="back_cards_num">0</span>枚</div>
            <div class="back card_image_frame">
                <?php echo $aDeckCardImages['back']; ?>
            </div>
            <div class="magic">マジック枚数:<span id="magic_cards_num">0</span>枚</div>
            <div class="magic card_image_frame">
                <?php echo $aDeckCardImages['magic']; ?>
            </div>
            <div class="super">スーパー枚数:<span id="super_cards_num">0</span>枚</div>
            <div class="super card_image_frame">
                <?php echo $aDeckCardImages['super']; ?>
            </div>
        </div>
        <div class="submit">
            <div>
                <input type="button" value="デッキ登録" />
            </div>
        </div>
        <label class="controlls">
            <input type="checkbox" class="switchSummary" />カード名を表示
        </label>
        <div class="card_catalog clearfix">
            <?php echo $sCardCatalog; ?>
        </div>
    </form>
</div>
