<?php
$aUserInfo = Common::checkLogin();

$sMessageHtml = '';
if (isset($this->sDispMessage)) {
    $sMessageHtml = <<<_eos_
<div class="message">
    {$this->sDispMessage}
</div>

_eos_;
}

$sNewLink = '';
if (isset($this->bDeckEdit) && $this->bDeckEdit) {
    $sNewLink = <<<_eos_
<div class="edit_link">
    <a href="/deck/edit/">デッキ新規作成</a>
</div>

_eos_;
}

$aPageInfo = array(
    'page_cd'   => 'deck_list',
    'user_id'   => $aUserInfo['user_id'],
);
if (isset($this->bGameStandby) && $this->bGameStandby) {
    $aPageInfo['page_cd'] = 'game_standby';
    $aPageInfo['game_field_id'] = $this->iGameFieldId;
} else if (isset($this->bGameStart) && $this->bGameStart) {
    $aPageInfo['page_cd'] = 'game_start';
    $aPageInfo['game_field_id'] = $this->iGameFieldId;
}
$sPageInfoHtml = "<div id='page_info' style='display:none;'";
foreach ($aPageInfo as $key => $val) {
    $sPageInfoHtml .= " {$key}='{$val}'";
}
$sPageInfoHtml .= ' ></div>';

$sDeckListHtml = '<div id="deck_list_frame" class="clearfix">';
foreach ($this->aDeckList as $deckId => $val) {
    $sDeckLink = '';
    if (isset($this->bGameStandby) && $this->bGameStandby) {
        $sDeckLink = <<<_eos_
    <div class="edit_link clearfix">
        <form action="/game/standby/" method="post">
            <input type="submit" value="このデッキを使ってゲームを始める" />
            <input type="hidden" name="deck_id" value="{$deckId}" />
        </form>
    </div>

_eos_;
    } else if (isset($this->bGameStart) && $this->bGameStart) {
        $sDeckLink = <<<_eos_
    <div class="edit_link clearfix">
        <form action="/game/start/" method="post">
            <input type="submit" value="このデッキを使ってゲームを受ける" />
            <input type="hidden" name="game_field_id" value="{$this->iGameFieldId}" />
            <input type="hidden" name="deck_id" value="{$deckId}" />
        </form>
    </div>

_eos_;
    } else if ($val['owner_id'] != null && $val['owner_id'] == $aUserInfo['user_id']) {
        $sDeckLink = <<<_eos_
    <div class="edit_link mine clearfix">
        <a href="/deck/edit/{$deckId}/">デッキ編集</a>
    </div>

_eos_;
    }
    $sCardListHtml = '';
    foreach ($val['cards'] as $listCard) {
        for ($i = 0 ; $i < $listCard['num'] ; $i++)
        $sCardListHtml .= <<<_eos_
        <div class="card_image">
            <img src="/images/card/card.jpg" original-src="/images/card/{$listCard['image_file_name']}" alt="{$listCard['card_name']}" />
        </div>

_eos_;
    }
    foreach ($val as $key => $v) {
        if (!is_array($v)) {
            $val[$key] = $this->escape($v);
        }
    }
    $sDeckListHtml .= <<<_eos_
<div class="deck_frame">
    <div class="deck_header clearfix">
        <div class="master_image">
            <img src="/images/card/{$val['master_image']}" alt="{$val['master_card_name']}" />
        </div>
        <div class="deck_summary">
            <div class="title">{$val['deck_name']}</div>
            <div class="owner">投稿者：{$val['owner_nick_name']}</div>
            <div class="struct">
                合計レアリティ:★<span class="rare_sum_num">{$val['rare_sum']}</span>
                最大レアリティ:★<span class="rare_max_num">{$val['rare_max']}</span><br />
                <!--
                デッキ枚数:<span class="deck_cards_num">{$val['deck_cards_num']}</span>枚
                -->
                前衛:<span class="front_cards_num">{$val['front_cards_num']}</span>枚
                後衛:<span class="back_cards_num">{$val['back_cards_num']}</span>枚
                マジック:<span class="magic_cards_num">{$val['magic_cards_num']}</span>枚
                スーパー:<span class="super_cards_num">{$val['super_cards_num']}</span>枚
            </div>
        </div>
    </div>
    <div class="card_list_frame clearfix">
        <div class="card_list clearfix">
{$sCardListHtml}
        </div>
    </div>
{$sDeckLink}
</div>

_eos_;
}
$sDeckListHtml .= '</div>';

$sMoreDeckList = '<input type="button" id="more_deck_list" page="1" value="もっと見る" />';

$sGameStartHtml = '';
if (isset($this->bGameStart) && $this->bGameStart) {
    $sGameStartHtml = <<<_eos_
<div class="message">
    フィールド状況
</div>

_eos_;
    $sGameStartHtml .= '<div id="game_field_list_frame">';
    $sGameStartHtml .= $this->render('game_field_table.phtml');
    $sGameStartHtml .= '</div>';
}

echo $sGameStartHtml;
echo $sMessageHtml;
echo $sNewLink;
echo $sDeckListHtml;
echo $sMoreDeckList;
echo $sNewLink;
echo $sPageInfoHtml;
