<?php
    $aConf = Zend_Registry::get('config');

    $aCardInfo = $this->aCardInfo;

    $aPosId = array(
        0 => array(
            'enemyBack2',
            'enemyPlayersInfo',
            'enemyBack1',
        ),
        1 => array(
            'enemyFront2',
            'enemyMaster',
            'enemyFront1',
        ),
        2 => array(
            'myFront1',
            'myMaster',
            'myFront2',
        ),
        3 => array(
            'myBack1',
            'myPlayersInfo',
            'myBack2',
        ),
    );

    $aCards = array();
    foreach ($aCardInfo['field'] as $iGameCardId => $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $sOwner = 'my';
        } else {
            $sOwner = 'enemy';
        }
        $pos = $sOwner . $val['position'];

        $sStatusDetail = '';
        if ($val['standby_flg']) {
            $sLv = '?';
            $sHp = '?';
            $val['image_file_name'] = 'card.jpg';
            $val['card_name'] = 'カードヒーロー';
            $sStatusDetail .= '<div standby_flg=1></div>';
        } else {
            $sLv = $val['lv'];
            $sHp = $val['hp'];
        }
        $sLvHp  = '<span class="mini-font">LV</span><span class="lv">' . $sLv . '</span>';
        $sLvHp .= '<span class="mini-font">HP</span><span class="hp">' . $sHp . '</span>';

        $sEffect  = '<span class="power"></span>';
        $sEffect .= '<span class="shield"></span>';
        $sEffect .= '<span class="magic"></span>';
        $sEffect .= '<span class="charge"></span>';
        $aEffectFlags = array();
        $aSt = array();
        if (isset($val['status']) && $val['status'] != '') {
            foreach ($val['status'] as $aStatusVal) {
                switch ($aStatusVal['type']) {
                    case '!':
                        $aEffectFlags['charge'] = true;
                        break;
                    case 'P':
                        $aEffectFlags['power'] = true;
                        break;
                    case 'S':
                        $aEffectFlags['shield'] = true;
                        break;
                    case 'M':
                        $aEffectFlags['magic'] = true;
                        break;
                }
                $aSt[$aStatusVal['id']]=array(
                        'status_id'=>$aStatusVal['id'],
                        'turn_count'=>$aStatusVal['turn'],
                        'param1'=>$aStatusVal['param1'],
                        'param2'=>$aStatusVal['param2'],
                );
                $sStatusDetail .= <<<_html_
                                <div class="status_row"
                                    status_id="{$aStatusVal['id']}"
                                    turn_count="{$aStatusVal['turn']}"
                                    param1="{$aStatusVal['param1']}"
                                    param2="{$aStatusVal['param2']}"></div>
_html_;
            }
            $sStatusDetail = preg_replace('/^\s+/', '', $sStatusDetail);
        }
        if (isset($aEffectFlags['charge'])) {
            $sEffect = str_replace('"charge">', '"charge">！', $sEffect);
        }
        if (isset($aEffectFlags['power'])) {
            $sEffect = str_replace('"power">', '"power">P', $sEffect);
        }
        if (isset($aEffectFlags['shield'])) {
            $sEffect = str_replace('"shield">', '"shield">S', $sEffect);
        }
        if (isset($aEffectFlags['magic'])) {
            $sEffect = str_replace('"magic">', '"magic">M', $sEffect);
        }
        $aMonsterData[$pos] = <<<_html_
                    <td id="{$pos}" class="monster_space" monster_id="{$val['monster_id']}" card_id="{$val['card_id']}" game_card_id="{$iGameCardId}">
                        <div class="pict">
                            <img class="card_image" src="/images/card/card.jpg" original-src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
                        </div>
                        <div class="param">
                            {$sLvHp}<br />
                            {$sEffect}
                            <div class="status_hidden_param" style="display:none;">
                                {$sStatusDetail}
                            </div>
                        </div>
                    </td>

_html_;
        $aCards[$iGameCardId] = array(
            'game_card_id'      => $iGameCardId,
            'card_id'           => $val['card_id'],
            'monster_id'        => $val['monster_id'],
            'owner'             => $sOwner,
            'pos_category'      => 'field',
            'sort_no'           => 0,
            'pos_id'            => $pos,
            'hp'                => $val['hp'],
            'standby_flg'       => $val['standby_flg'],
            'skill_disable_flg' => 0,
            'act_count'         => 0,
            'lvup_standby'      => 0,
            'status'            => $aSt,
        );
        if (isset($val['next_game_card_id']) && $val['next_game_card_id'] != '') {
            $aCards[$iGameCardId]['next_game_card_id'] = $val['next_game_card_id'];
        }
    }

    $sMyHandHtml = '';
    $sHandCards = '';
    $aHandCount = array(
        'my'    => 0,
        'enemy' => 0,
    );
    $iSortNo = 0;
    foreach ($this->aCardInfo['hand'] as $iGameCardId => $val) {
        $sOwner = ($aCardInfo['field_info']['turn'] == $val['owner']) ? 'my' : 'enemy';
        if ($sOwner == 'my') {
            $sMyHandHtml .= <<<_html_
                <div class="hand_card" game_card_id="{$iGameCardId}" card_id="{$val['card_id']}">
                    <img src="/images/card/card.jpg" original-src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
                </div>

_html_;
        }
        $aHandCount[$sOwner]++;
        $sHandCards .= <<<_html_
<div class="hand_card"
    game_card_id="{$iGameCardId}"
    card_id="{$val['card_id']}"
    owner="{$val['owner']}" ></div>

_html_;
        $aCards[$iGameCardId] = array(
            'game_card_id'  => $iGameCardId,
            'card_id'       => $val['card_id'],
            'owner'         => $sOwner,
            'pos_category'  => 'hand',
            'sort_no'       => $iSortNo++,
        );
    }
    $sMyHandHtml = preg_replace('/^\s+/', '', $sMyHandHtml);

    if ($aCardInfo['field_info']['turn'] == 1) {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone1'],
            'enemy' => $aCardInfo['field_info']['stone2'],
        );
    } else {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone2'],
            'enemy' => $aCardInfo['field_info']['stone1'],
        );
    }
    $aMonsterData['enemyPlayersInfo'] = <<<_html_
                    <td id="enemyPlayersInfo">
                        <div class="num_info stone">
                            <img src="/images/stone.png" alt="stone" />：
                            <span>{$aStoneCount['enemy']}</span>
                        </div>
                        <div class="num_info hand">
                            <img src="/images/card/card.jpg" alt="hand" />：
                            <span>{$aHandCount['enemy']}</span>
                        </div>
                        <div class="num_info deck">
                        </div>
                        <div class="num_info used">
                        </div>
                    </td>

_html_;
    $aMonsterData['myPlayersInfo'] = <<<_html_
                    <td id="myPlayersInfo">
                        <div class="num_info stone">
                            <img src="/images/stone.png" alt="stone" />：
                            <span>{$aStoneCount['my']}</span>
                        </div>
                        <div class="num_info hand">
                            <img src="/images/card/card.jpg" alt="hand" />：
                            <span>{$aHandCount['my']}</span>
                        </div>
                        <div class="num_info deck">
                        </div>
                        <div class="num_info used">
                        </div>
                    </td>

_html_;

    if (!empty($aCardInfo['deck'])) {
        foreach ($aCardInfo['deck'] as $iGameCardId => $val) {
            $sOwner = ($aCardInfo['field_info']['turn'] == $val['owner']) ? 'my' : 'enemy';
            $aCards[$iGameCardId] = array(
                'game_card_id'  => $iGameCardId,
                'card_id'       => $val['card_id'],
                'owner'         => $sOwner,
                'pos_category'  => 'deck',
                'sort_no'       => $iSortNo++,
            );
        }
    }

    if (!empty($aCardInfo['used'])) {
        foreach ($aCardInfo['used'] as $iGameCardId => $val) {
            $sOwner = ($aCardInfo['field_info']['turn'] == $val['owner']) ? 'my' : 'enemy';
            $aCards[$iGameCardId] = array(
                'game_card_id'  => $iGameCardId,
                'card_id'       => $val['card_id'],
                'owner'         => $sOwner,
                'pos_category'  => 'used',
                'sort_no'       => $iSortNo++,
            );
        }
    }

    $sConditionInfoDiv = <<<_html_
        <div
            turn_num='{$aCardInfo['field_info']['turn']}'
            turn_count='{$aCardInfo['field_info']['turn_count']}'
            replay_flg='{$this->bReplayFlg}'
            no_arrange='{$aConf->web->no_arrange}'
            initial_deck='{$aConf->game->deck->max}'
        ></div>

_html_;

    $layout = Zend_Registry::get('layout');
    if (!isset($layout->javascriptCode)) {
        $layout->javascriptCode = '';
    }
    $sCardsInfoJson = json_encode($aCards);
    $sQueueInfoJson = json_encode($this->aQueue);
    $layout->javascriptCode .= <<<_javascript_
function getCardsJson() {
    return JSON.parse('{$sCardsInfoJson}');
}
function getQueueJson() {
    return JSON.parse('{$sQueueInfoJson}');
}

_javascript_;

    $sMovieConsole = '';
    $sTurnEndHtml = '';
    if ($this->bReplayFlg) {
        $sMovieConsole = <<<_html_
<div id="movie_controll">
                <div>
                    <input type="button" class="play" value="▶再生" />
                    <input type="button" class="pause" value="■一時停止" />
                    <input type="button" class="toggle_log" value="全ログ表示" />
                </div>
                <div>
                    <ul id="log_list">
                    </ul>
                </div>
            </div>

_html_;
    } else {
        $sTurnEndHtml = <<<_html_
    <div id="buttons_frame">
        <div class="cancel_button">
            キャンセル
        </div>
        <div class="turn_end_button">
            ターンエンド
        </div>
    </div>

_html_;
    }

    $sFieldHtml = "<table id='game_field'>\n";
    foreach ($aPosId as $aLine) {
        $sFieldHtml .= "                <tr>\n";
        foreach ($aLine as $posId) {
            if (!isset($aMonsterData[$posId])) {
                $aMonsterData[$posId] = "                    <td id='{$posId}' class='monster_space'><div class='pict'></div></td>\n";
            }
            $sFieldHtml .= $aMonsterData[$posId];
        }
        $sFieldHtml .= "                </tr>\n";
    }
    $sFieldHtml .= "            </table>\n";

    if (!empty($this->sAd)) {
        $sAd = <<<_html_
    <div class="click_ad">
        {$this->sAd}
        <div class="exp">↑↑↑こちらの広告は<a href="/user/login-input/">ログイン</a>すると消えます。↑↑↑<br />&nbsp;</div>
    </div>

_html_;
    } else {
        $sAd = '';
    }
?>
<div id="game_field_wrapper">
    <div id="game_infomation_frame">
        <div class="label">
            Game Infomation
        </div>
        <div class="info">
        </div>
    </div>
    <div id="responcive_frame" class="clearfix">
        <div id="primary_part">
            <?=$sFieldHtml?>
            <div id="hand_card" class="clearfix">
                <?=$sMyHandHtml?>
            </div>
            <?=$sMovieConsole?>
        </div>
        <div id="secondary_part">
            <div id="card_info">
                <div id="card_info_frame">
                    <div class="card_info_title">
                        Card Infomation
                    </div>
                    <div class="card_summary clearfix">
                        <div class="card_image"></div>
                        <div class="card_name"></div>
                        <div class="dtl_link"></div>
                    </div>
                    <div class="act_commands">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?=$sAd?>
    <?=$sTurnEndHtml?>
    <input type="BUTTON" class="disp_button toggle_setting" value="設定" />
    <div class="settings">
        <input type="BUTTON" class="toggle_setting first" value="設定非表示" />
        <div class="setting_item first"></div>
        <div class="setting_item animation_speed">
            <span>アニメーションスピード</span><br/>
            <input type="RADIO" name="animation_speed" value="1"   />一瞬
            <input type="RADIO" name="animation_speed" value="100" />速い
            <input type="RADIO" name="animation_speed" value="300" />普通
            <input type="RADIO" name="animation_speed" value="500" />遅い
        </div>
        <div class="setting_item old_animation_speed">
            <span>前ターンのアニメーションスピード</span><br/>
            <input type="RADIO" name="old_animation_speed" value="1"   />普通に流す
            <input type="RADIO" name="old_animation_speed" value="200" />じっくり流す
        </div>
        <div class="setting_item actor_auto_change">
            <span>カード選択切り替え</span><br/>
            <span class="mini-font">不適切な対象を選択した時、Card Infomationを選択したカードに切り替える</span><br/>
            <input type="RADIO" name="actor_auto_change" value="all"    />全て
            <input type="RADIO" name="actor_auto_change" value="hand"   />手札のみ
            <input type="RADIO" name="actor_auto_change" value="field"  />フィールドのみ
            <input type="RADIO" name="actor_auto_change" value="off"    />OFF
        </div>
        <div class="setting_item animation_speed">
            <span>アラートメッセージ</span><br/>
            <input type="RADIO" name="alert_popup" value="1" />アラート表示
            <input type="RADIO" name="alert_popup" value="0" />アラート非表示
        </div>
        <input type="BUTTON" class="toggle_setting last" value="設定非表示" />
    </div>

    <div class="hidden_cards_info">
        <?=$sConditionInfoDiv?>
    </div>
    <form name="form_current_field" method="post" action="/game/turn-end/">
        <input type="hidden" name="game_field_id" value="<?=$this->iGameFieldId?>" />
        <input type="hidden" name="referer" value="<?=$this->sReferer?>" />
    </form>
</div>
<?php
if ($this->bReplayFlg) {
    $sTitle = preg_replace(';<span\s?.*?>(.*?)</span>;', '${1}', $aCardInfo['field_info']['title_str']);
    $sTitle = preg_replace(';\s*\d+ターン目;', '', $sTitle);
    $aRichSnipet = array(
        '@context'  => 'http://schema.org',
        '@type'     => 'Game',
        'about'     => $sTitle,
        'accountablePerson' => array(
            array(
                'name'  => $aCardInfo['field_info']['nick_name'],
            ),
            array(
                'name'  => $aCardInfo['field_info']['opponent_name'],
            ),
        ),
    );
    $sRichSnipet = json_encode($aRichSnipet);
    echo "<script type='application/ld+json'>{$sRichSnipet}</script>";
}
?>
