<?php
$self = $this;
$fnPaging = function ($sUrlBase, $bDispBeforePage, $bDispLastPage) use ($self) {
    // ページングリンク生成処理

    $iFieldsInPage = 10;    // 1ページ当たりに表示されるフィールドの数
    $iDispLinkRange = 2;    // 前後何ページまでページングするか

    $sUrlBase = preg_replace(';/$;', '', $sUrlBase);

    // 合計で何ページ存在してるか計算
    $iPages = ceil((float)$self->nFields / (float)$iFieldsInPage);

    // ページング対象のページ番号の最大値・最小値を計算
    $aDispPageNum = array(
        'min'   => max($self->nPage - $iDispLinkRange, 1),  // 1未満だったら1にする
        'max'   => min($self->nPage + $iDispLinkRange, $iPages),    // 全ページ数を超えるならそれに合わせる
    );

    $sPageLinkTag = "<div class='page_link'>\n";

    if ($bDispBeforePage && 1 < $self->nPage) {
        $iBeforePage = $self->nPage - 1;
        $sPageLinkTag .= "<span><a href='{$sUrlBase}/{$iBeforePage}/'>前へ</a></span>\n";
    }

    if (1 < $aDispPageNum['min']) {
        $sPageLinkTag .= "<a href='{$sUrlBase}/'><span class='first_page_link'>1</span></a>...\n";
    }

    for ($i = $aDispPageNum['min'] ; $i <= $aDispPageNum['max'] ; $i++) {
        if ($i == $self->nPage) {
            $sPageLinkText = "<span><strong>{$i}</strong></span>";
        } else {
            if ($i == 1) {
                $sUrl = $sUrlBase . '/';
            } else {
                $sUrl = $sUrlBase . '/' . $i . '/';
            }
            $sPageLinkText = "<a href='{$sUrl}'><span>{$i}</span></a>\n";
        }
        $sPageLinkTag .= "{$sPageLinkText}\n";
    }

    if ($bDispLastPage && $aDispPageNum['max'] < $iPages) {
        $sPageLinkTag .= "...<a href='{$sUrlBase}/{$iPages}/'><span>{$iPages}</span></a>\n";
    }

    if ($self->nPage < $iPages) {
        $iNextPage = $self->nPage + 1;
        $sPageLinkTag .= "<a href='{$sUrlBase}/{$iNextPage}/'><span class='next_page_link'>次へ</span></a>\n";
    }

    $sPageLinkTag .= "</div>\n";

    return $sPageLinkTag;
};

// ページングリンク生成処理
if (isset($this->bMine) && $this->bMine) {
    $sPageLinkTag = $fnPaging('/game/my-turn/', false, false);
} else if (isset($this->bStandby) && $this->bStandby) {
    $sPageLinkTag = $fnPaging('/game/lobby/', false, false);
} else if (isset($this->bLast) && $this->bLast) {
    $sPageLinkTag = $fnPaging('/game/last/', false, false);
} else if (isset($this->bMovie) && $this->bMovie) {
    $sPageLinkTag = $fnPaging('/game/movie/', false, false);
} else {
    $sPageLinkTag = $fnPaging('/game/', false, false);
}

$sSelectOldFieldDispray = '';
$sBackgroundStyle = '';
$sDescription = '返信の無いフィールドの一覧です。';
$sSelectOldFieldDispray = <<<_eos_
<div class="old_field_disp_select_frame">
    返信済みフィールド：
    <select class="old_field_disp_select">
        <option value="normal" selected="selected">普通に表示</option>
        <option value="small">控えめに表示</option>
        <option value="hide">圧縮して表示</option>
    </select>
</div>

_eos_;
if (!empty($this->bMine)) {
    // 自分宛てフィールド一覧
    $aUserInfo = Common::checkLogin();
    if (!$aUserInfo) {
        $sUserName = 'あなた';
    } else {
        $sUserName = $aUserInfo['nick_name'] . 'さん';
    }
    $sBackgroundStyle = '<style>#game_field_list_wrapper { background-color:#eeffee !important; }</style>';
    $sH1Text = 'あなたへの返信一覧';
    $sDescription = $sUserName . 'の投稿に対して返信されたフィールドの一覧です。<br />さらにフィールドを返信して、対戦の続きをお楽しみ下さい。';
    $sLastLink = "<a class='zabuton_blue' href='/game/'>全フィールド一覧はこちら</a>";
} else if (!empty($this->bLobby)) {
    // 開始前フィールド一覧
    $sBackgroundStyle = '<style>#game_field_list_wrapper { background-color:#ffddff !important; }</style>';
    $sH1Text = '開始前フィールド一覧';
    $sLastLink = "<a class='zabuton_red' href='/game/new/'>新規ゲームを立てる場合はこちら</a>";
    $sLastLink .= "<a class='zabuton_blue' href='/game/'>全フィールド一覧はこちら</a>";
    $sDescription = '現在、対戦相手受付中のフィールド一覧です。<br />こちらから返信する事でゲームを開始できます。';
    $sSelectOldFieldDispray = '';
} else if (!empty($this->bLast)) {
    // 未返信フィールド一覧
    $sBackgroundStyle = '<style>#game_field_list_wrapper { background-color:#ffeeee !important; }</style>';
    $sH1Text = '未返信フィールド一覧';
    $sLastLink = "<a class='zabuton_blue' href='/game/'>全フィールド一覧はこちら</a>";
    $sSelectOldFieldDispray = '';
} else if (!empty($this->bMovie)) {
    // リプレイ
    $sBackgroundStyle = '<style>#game_field_list_wrapper { background-color:#ffffee !important; }</style>';
    $sH1Text = 'リプレイ鑑賞';
    $sLastLink = "<a class='zabuton_blue' href='/game/'>通常のフィールド一覧はこちら</a>";
    $sDescription = '決着のついた対戦を、ゲーム開始時から動画風に再現する事ができます。';
    $sSelectOldFieldDispray = '';
} else {
    // 通常の一覧
    $sH1Text = 'フィールド一覧';
    $sDescription = '投稿されたフィールドの一覧です。';
    if (isset($this->bNewFieldCommited) && $this->bNewFieldCommited) {
        $sDescription = '新規ゲームの投稿が完了しました。';
    }
    $sLastLink  = "<a class='zabuton_red' href='/game/last/'>未返信フィールドの一覧へ</a>";
    $sLastLink .= "<a class='zabuton_yellow' href='/game/movie/'>対戦リプレイの鑑賞へ</a>";
    $sLastLink .= "<a class='zabuton_pink' href='/game/lobby/'>開始前フィールドの一覧へ</a>";
    $sLastLink .= "<a class='zabuton_green' href='/game/my-turn/'>あなたへの返信一覧へ</a>";
}

$sFields = '';
$i = 0;
foreach ($this->aCardInfoArray as $aCardInfo) {
    $this->aCardInfoInField = $aCardInfo;
    $aFieldInfo = $aCardInfo['field_info'];
    $sLinkTitle = "{$aFieldInfo['title_str']} [{$aFieldInfo['upd_date']}]";
    $sHref = "/game/receive/{$aFieldInfo['game_field_id']}/";
    if (!empty($aFieldInfo['started_flg'])) {
        if (!empty($this->bMovie)) {
            $sHref = "/game/replay/{$aFieldInfo['game_field_id']}/";
        } else {
            $sHref = "/game/field/{$aFieldInfo['game_field_id']}/";
        }
    }
    if (!empty($this->bMine)) {
        $sHref .= '?referer=mytrun';
    } else if ($this->bLast) {
        $sHref .= '?referer=last';
    }
    $sFields .= <<<_eos_
<div class="game_field_info">
    <div class="field_title">
        <a href="{$sHref}">{$sLinkTitle}</a>
    </div>
    {$this->render('game_field_table.phtml')}
</div>

_eos_;
    if ($i % 3 == 0 && !empty($this->aAd)) {
        // 広告追加
        $ad = array_pop($this->aAd);
        $sFields .= <<<_eos_
<div class="click_ad" style="width:100%;">
    {$ad}
</div>

_eos_;
    }
    $i++;
}
?>

<div id="game_field_list_wrapper">
<?php
echo $sBackgroundStyle;
echo "<h1>{$sH1Text}</h1>";
echo "<div class='page_description'>";
echo $sDescription;
echo "</div>";
echo "<div class='game_list_link clearfix'>";
echo $sLastLink;
echo "</div>";
if (empty($this->aCardInfoArray)) {
    echo '<div class="no-fields">まだフィールドが投稿されていません。</div>' . "\n";
} else {
    echo $sSelectOldFieldDispray;
    echo $sPageLinkTag;
    echo $sFields;
    echo $sPageLinkTag;
    echo $sSelectOldFieldDispray;
    echo "<div class='game_list_link clearfix'>";
    echo $sLastLink;
    echo "</div>";
}
?>
</div>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "item": {
            "@id": "/",
            "name": "TOP"
        }
    }, {
        "@type": "ListItem",
        "position": 2,
        "item": {
            "@id": "/game/",
            "name": "ゲームフィールド一覧"
        }
    }]
}
</script>
