<?php
$iFieldsInPage = 10;    // 1ページ当たりに表示されるフィールドの数
$iDispLinkRange = 2;    // 前後何ページまでページングするか

// 合計で何ページ存在してるか計算
$iPages = (int)(($this->nFields - 1) / $iFieldsInPage) + 1;

// ページング対象のページ番号の最大値・最小値を計算
$aDispPageNum = array(
    'min'   => max($this->nPage - $iDispLinkRange, 1),  // 1未満だったら1にする
    'max'   => min($this->nPage + $iDispLinkRange, $iPages),    // 全ページ数を超えるならそれに合わせる
);

$sPageLinkTag = "<div class='page_link'>\n";
if (1 < $aDispPageNum['min']) {
    $sPageLinkTag .= <<<_eos_
    <span><a href="/game/">1...</a></span>

_eos_;
}

for ($i = $aDispPageNum['min'] ; $i <= $aDispPageNum['max'] ; $i++) {
    if ($i == $this->nPage) {
        $sPageLinkText = "<b>{$i}</b>";
    } else {
        $sPageLinkText = "<a href='/game/{$i}/'>{$i}</a>";
    }
    $sPageLinkTag .= "<span>{$sPageLinkText}</span>\n";
}

if ($aDispPageNum['max'] < $iPages) {
    $sPageLinkTag .= <<<_eos_
    <span><a href="/game/{$iPages}/">...{$iPages}</a></span>

_eos_;
}
$sPageLinkTag .= "</div>\n";

$sSelectOldFieldDispray = <<<_eos_
<div class="old_field_disp_select_frame">
    返信済みフィールド：
    <select class="old_field_disp_select">
        <option value="normal" selected="selected">普通に表示</option>
        <option value="small">控えめに表示</option>
        <option value="hide">圧縮して表示</option>
    </select>
</div>

_eos_;
?>

<div id="game_field_list_frame">
<?php
if (empty($this->aCardInfoArray)) {
    echo '<div class="no-fields">まだフィールドが投稿されていません。</div>' . "\n";
} else {
    echo $sSelectOldFieldDispray;
    echo $sPageLinkTag;
    foreach ($this->aCardInfoArray as $aCardInfo) {
        $this->aCardInfoInField = $aCardInfo;
        $aFieldInfo = $aCardInfo['field_info'];
        $sLinkTitle = "{$aFieldInfo['title_str']} [{$aFieldInfo['start_date']}～]";
        $sHref = "/game/receive/{$aFieldInfo['game_field_id']}/";
        if (isset($aFieldInfo['started_flg']) && $aFieldInfo['started_flg']) {
            $sHref = "/game/field/{$aFieldInfo['game_field_id']}/";
        }
        echo <<<_eos_
<div class="game_field_info">
    <div class="field_title">
        <a href="{$sHref}">{$sLinkTitle}</a>
    </div>
    {$this->render('game_field_table.phtml')}
</div>

_eos_;
    }
    echo $sPageLinkTag;
    echo $sSelectOldFieldDispray;
}
?>
</div>
