<div class="card_data clearfix">
<?php
    foreach ($this->aCardInfo['image_info'] as $val) {
        echo <<<_eos_
    <div class="card_image">
        <img src="{$val['image_file_name']}" width=50 height=50 alt="{$val['card_name']}" />
    </div>

_eos_;
    }
?>
    <div class="card_text">
        <div class="card_name"><?php
            echo $this->aCardInfo['card_name'];
            echo '　★' . $this->aCardInfo['rare'];
        ?></div>
        <div class="card_type"><?php
            echo $this->aCardInfo['category_name'];
            if (isset($this->aCardInfo['before_monster_name'])) {
                echo "　<span class='before_monsters'>{$this->aCardInfo['before_monster_name']}</span>から進化";
            }
        ?></div>
        <div class="card_caption"><?php echo $this->aCardInfo['caption']; ?></div>
    </div>
</div>
<?php
echo $this->render($this->template);
?>
