<?php
if (empty($this->message)) {
    $this->message = '';
}

$sInput = '';
foreach ($this->aCols as $key => $val) {
    $sAttrValue = '';
    if (isset($this->aInput[$key])) {
        $sAttrValue = $this->aInput[$key];
    }
    $sInput .= <<<_eos_
        <div class="clearfix">
            <div class="column_name">{$val}：</div>
            <div class="input_box">
                <input class="wide" type="text" value="{$sAttrValue}" name="{$key}" />
            </div>
        </div>

_eos_;
}
?>
<div id="regist_input">
    <h1>新規ユーザー登録</h1>
    <form name="regist_form" action="/user/regist-confirm/" method="post">
        <div id="message"><?=$this->message?></div>
        <?=$sInput?>
        <div class="submit"><input type="button" value="確認画面へ" /></div>
    </form>
    <ul class="warning">
    <li>Twitter IDを入力すると、<a href="<?=$this->sTwitterBotUrl?>" target="_blank">bot</a>から＠ツイートが飛びます。<br /> 他人に見せたくないIDは登録しないでください。</li>
    </ul>
</div>
