<?php
if (!isset($this->message)) {
    $this->message = '';
}

$sDivs = '';
foreach ($this->aInput as $key => $val) {
    $sColName = '';
    $sDispVal = $val;
    if ($key == 'password') {
        $sDispVal = preg_replace('/./', '*', $val);
    }
    if (isset($this->aCols[$key])) {
        $sColName = $this->aCols[$key];
    }
    $sDivs .= <<<_eos_
    <div class="clearfix">
        <div class="column_name">{$sColName}：</div>
        <div class="input_box">{$sDispVal}</div>
        <input type="hidden" name="{$key}" value="{$val}" />
    </div>

_eos_;
}
$sConfirmMessage = '上記内容で更新します。よろしいですか？';
$sRegistButton = '<input type="button" to_page="/user/update/" value="更新" />'; 
if (isset($this->sConfirmErrorMessage)) {
    $sConfirmMessage = $this->sConfirmErrorMessage;
    $sRegistButton = '';
}
?>
<div id="update_confirm">
    <h1>ユーザー情報更新</h1>
    <form name="regist_form" action="/user/regist/" method="post">
<?php echo <<<_eos_
        <div id="message">{$this->message}</div>
        {$sDivs}
        <span class="confirm">{$sConfirmMessage}</span>
        <div class="submit">
            <input type="button" to_page="/user/update-input/" value="戻る" />
            {$sRegistButton}
        </div>

_eos_;
?>
    </form>
</div>
