<?php
$conf = Zend_Registry::get('config');

$l = $this->layout();

// title
$sTitle = '';
if (!empty($l->title)) {
    $sTitle = $l->title . ' - ';
}
$sTitle = $conf->web->title->prefix . $sTitle;

// description
$sDescription = '';
if (!empty($l->description)) {
    $sDescription = $l->description;
}

// canonical
$sDefaultCanonical = preg_replace('/\?.*$/', '', $_SERVER['REQUEST_URI']);
$sCanonical = "<link rel='canonical' href='{$sDefaultCanonical}' />\n";
if (!empty($l->canonical)) {
    $sCanonical = "<link rel='canonical' href='{$l->canonical}' />\n";
}

// noindex
$sNoIndex = '';
if ($conf->web->noindex || isSet($l->noindex)) {
    $sNoIndex = '<meta name="robots" content="noindex,follow" />' . "\n";
}

// stylesheet
$sStylesheet = '';
if (isSet($l->stylesheet)) {
    foreach ($l->stylesheet as $key => $val) {
        if ($val != '') {
            $sStylesheet .= "<link rel=\"stylesheet\" type=\"text/css\" href=\"{$val}\" media=\"all\" />\n";
        }
    }
}
?>
<meta charset="UTF-8" />
<title><?php echo $sTitle; ?>カードヒーロー@スマホ</title>
<meta name="keywords" content="カードヒーロー,スマホ" />
<meta name="description" content="<?php echo $sDescription; ?>" />
<meta name="viewport" content="width=device-width,user-scalable=yes,initial-scale=1,minimum-scale=1" />
<link rel="shortcut icon" href="/images/favicon.ico" />
<?php echo $sNoIndex; ?>
<?php echo $sCanonical; ?>
<link rel="stylesheet" type="text/css" href="/css/screen.css?ver=20151224" media="all" />
