<?php
$conf = Zend_Registry::get('config');

$l = $this->layout();

// javascript
$sJavascript = '';

if (isSet($l->javascript)) {
    foreach ($l->javascript as $key => $val) {
        if ($val != '') {
            $sJavascript .= "<script src=\"{$val}\"></script>\n";
        }
    }
}
if (isSet($l->javascriptCode)) {
    $sJavascript .= <<<_eos_
<script type="text/javascript">
<!--
{$l->javascriptCode}
-->
</script>

_eos_;
}

if (empty($_GET['from']) || preg_match(';https?//;', $_GET['from']) === false) {
    if (APPLICATION_ENV == 'production') {
        // Googleアナリティクスタグ
        $sJavascript .= <<<_eos_
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53206929-1', 'auto');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');

</script>

_eos_;
    } else {
        $sJavascript .= "<!-- Google Analytics -->\n";
    }
}
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="/js/jquery.color-2.1.2.min.js"></script>
<script src="/js/to_kana_zenkaku.js"></script>
<?php echo $sJavascript; ?>
