<?php
$conf = Zend_Registry::get('config');

$l = $this->layout();

// javascript
$sJavascript = '';

if (isSet($l->javascript)) {
    foreach ($l->javascript as $key => $val) {
        if ($val != '') {
            $sJavascript .= "<script src=\"{$val}\"></script>\n";
        }
    }
}
if (isSet($l->javascriptCode)) {
    $sJavascript .= <<<_eos_
<script type="text/javascript">
<!--
{$l->javascriptCode}
-->
</script>

_eos_;
}
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="/js/jquery.color-2.1.2.min.js"></script>
<script src="/js/to_kana_zenkaku.js"></script>
<script src="/js/jquery.colorbox-min.js"></script>
<script>
$(function () {
    $('.colorbox-iframe').colorbox({
        iframe: true,
        width: '90%',
        height: '90%',
        maxWidth: '720px',
    });
})
</script>
<?php echo $sJavascript; ?>
