<?php
$conf = Zend_Registry::get('config');

$l = $this->layout();

// title
$sTitle = '';
if (!empty($l->title)) {
    $sTitle = $l->title . ' - ';
}
$sTitle = $conf->web->title->prefix . $sTitle;

// description
$sDescription = '';
if (!empty($l->description)) {
    $sDescription = preg_replace(';<.*?>(.*?)</.*?>;', '$1', $l->description);
}

// canonical
$sDefaultCanonical = preg_replace('/\?.*$/', '', $_SERVER['REQUEST_URI']);
$sCanonical = "<link rel='canonical' href='{$sDefaultCanonical}' />\n";
if (!empty($l->canonical)) {
    $sCanonical = "<link rel='canonical' href='{$l->canonical}' />\n";
}

// noindex
$sNoIndex = '';
if ($conf->web->noindex || isSet($l->noindex)) {
    $sNoIndex = '<meta name="robots" content="noindex,follow" />' . "\n";
}

// stylesheet
$sStylesheet = '';
if (isSet($l->stylesheet)) {
    foreach ($l->stylesheet as $key => $val) {
        if ($val != '') {
            $sStylesheet .= "<link rel=\"stylesheet\" type=\"text/css\" href=\"{$val}\" media=\"all\" />\n";
        }
    }
}

$sAnalytics = '';
if ((empty($_GET['from']) || preg_match(';https?//;', $_GET['from']) === false) && empty($l->bPreventAnalytics)) {
    if (APPLICATION_ENV == 'production') {
        // Googleアナリティクスタグ
        $sAnalytics = <<<_eos_
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53206929-1', 'auto');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');

</script>

_eos_;
    } else {
        $sAnalytics = "<!-- Google Analytics -->\n";
    }
}
?>
<meta charset="UTF-8" />
<title><?=$sTitle?>カードヒーロー@スマホ</title>
<meta name="keywords" content="カードヒーロー,スマホ" />
<meta name="description" content="<?=$sDescription?>" />
<meta name="viewport" content="width=device-width,user-scalable=yes,initial-scale=1,minimum-scale=1" />
<link rel="shortcut icon" href="/images/favicon.ico" />
<?=$sNoIndex?>
<?=$sCanonical?>
<link rel="stylesheet" type="text/css" href="/css/screen.css?ver=20160314" media="all" />
<?=$sAnalytics?>
