<?php
$conf = Zend_Registry::get('config');

$l = $this->layout();

// title
$sTitle = '';
if (isSet($l->title)) {
    $sTitle = $l->title . ' - ';
}
$sTitle = $conf->web->title->prefix . $sTitle;

// description
$sDescription = '';
if (isset($l->description)) {
    $sDescription = $l->description;
}

// canonical
$sDefaultCanonical = preg_replace('/\?.*$/', '', $_SERVER['REQUEST_URI']);
$sCanonical = "<link rel='canonical' href='{$sDefaultCanonical}' />\n";
if (isSet($l->canonical)) {
    $sCanonical = "<link rel='canonical' href='{$l->canonical}' />\n";
}

// noindex
$sNoIndex = '';
if ($conf->web->noindex || isSet($l->noindex)) {
    $sNoIndex = '<meta name="robots" content="noindex,follow" />' . "\n";
}

// stylesheet
$sStylesheet = '';
if (isSet($l->stylesheet)) {
    foreach ($l->stylesheet as $key => $val) {
        if ($val != '') {
            $sStylesheet .= "<link rel=\"stylesheet\" type=\"text/css\" href=\"{$val}\" media=\"all\" />\n";
        }
    }
}

// javascript
$sJavascript = '';

if (isSet($l->javascript)) {
    foreach ($l->javascript as $key => $val) {
        if ($val != '') {
            $sJavascript .= "<script type=\"text/javascript\" src=\"{$val}\" charset=\"UTF-8\"></script>\n";
        }
    }
}
if (isSet($l->javascriptCode)) {
    $sJavascript .= <<<_eos_
<script type="text/javascript">
<!--
{$l->javascriptCode}
-->
</script>

_eos_;
}

if (APPLICATION_ENV == 'production') {
    // Googleアナリティクスタグ
    $sJavascript .= <<<_eos_
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53206929-1', 'auto');
  ga('require', 'linkid', 'linkid.js');
  ga('send', 'pageview');

</script>

_eos_;
} else {
    $sJavascript .= "<!-- Google Analytics -->\n";
}
?>
<meta charset="UTF-8" />
<title><?php echo $sTitle; ?>カードヒーロー@スマホ</title>
<meta name="keywords" content="カードヒーロー,スマホ" />
<meta name="description" content="<?php echo $sDescription; ?>" />
<meta name="viewport" content="width=device-width,user-scalable=yes,initial-scale=1,minimum-scale=1" />
<link rel="shortcut icon" href="/images/favicon.ico" />
<?php echo $sNoIndex; ?>
<?php echo $sCanonical; ?>
<link rel="stylesheet" type="text/css" href="/css/screen.css?ver=20150628" media="all" />
<script type="text/javascript" src="/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="/js/jquery.color-2.1.2.min.js"></script>
<script type="text/javascript" src="/js/to_kana_zenkaku.js"></script>
<?php echo $sJavascript; ?>
