<?php $conf = Zend_Registry::get('config'); ?>
<br />
<div style="clear:both;"></div>
<div id="footer">
    <div class="footer_tweet">
        <?php if ($conf->web->footer->display_tweet) : ?>
        <a href="https://twitter.com.display/share" class="twitter-share-button" data-via="" data-lang="ja" data-count="none" data-hashtags="カードヒーロー">ツイート</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        <?php endif; ?>
        <span>
            カードヒーロー＠スマホ　制作/gitti <a class="blank_link" href="https://twitter.com/gittib_gittib" target="_blank">@gittib_gittib</a>
        </span>
    </div>
    <?php if (false) : ?>
    <div class="footer_ad">
        <div class="slide">
            <div class="ad_frame">
                <div style="width:120px">
                    <script type="text/javascript"> var nend_params = {"media":24587,"site":126385,"spot":332992,"type":1,"oriented":1}; </script>
                    <script type="text/javascript" src="http://js1.nend.net/js/nendAdLoader.js"></script>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php
if ($conf->web->footer->display_sql) {
    echo "<br />\n";
    echo Common::checkSQL();
}
?>
