<?php
    $conf = Zend_Registry::get('config');
    if (!isset($this->no_ad)) {
        $db = Zend_Registry::get('db');
        if (Common::checkUA() == 'pc') {
            $sUA = 'pc';
        } else {
            $sUA = 'smt';
        }
        $sub = $db->select()
            ->from(
                't_ad',
                array(
                    'ad_id',
                    'code',
                    'ad_comment',
                    'rank'  => new Zend_Db_Expr("dense_rank() over(partition by ad_group_id order by random())"),
                )
            )
            ->where('del_flg != 1')
            ->where('start_date <= now()')
            ->where('end_date >= now()')
            ->where('ad_type like ?', '%' . $sUA . '%')
            ->order(array(
                'random()',
            ));
        $sel = $db->select()
            ->from(
                array('sub' => $sub)
            )
            ->where('sub.rank = ?', 1)
            ->limit(5);

        $rslt = $db->fetchAll($sel);

        $sAd = '';
        foreach ($rslt as $val) {
            $sAd .= '<div>' . $val['code'] . '</div>';
        }


        $aAdHtml = array();
        $aAdHtml[] = <<<_eos_
    <div class="footer_ad">
        <div class="slide">
            <div class="ad_frame">
                {$sAd}
            </div>
        </div>
    </div>
    <script type="text/javascript" src="/js/jquery.mousewheel.min.js"></script>
    <script type="text/javascript" src="/js/perfect-scrollbar.jquery.min.js"></script>
    <script type="text/javascript">
        (function() {
            var iWidth = 10;
            $('.footer_ad img').each(function() {
                iWidth += $(this).width() + 10;
            });
            setTimeout(function () {
                $('.ad_frame').css('width', iWidth+'px');
                $('.footer_ad').perfectScrollbar();
            }, 1000);
        })();
    </script>

_eos_;

        if (Common::checkUA() != 'pc') {
            $aAdHtml[] = <<<_eos_
    <!-- nend -->
    <script type="text/javascript">
    var nend_params = {"media":24587,"site":126385,"spot":332992,"type":1,"oriented":1};
    </script>
    <script type="text/javascript" src="//js1.nend.net/js/nendAdLoader.js"></script>

_eos_;
        }

        $idx = rand() % count($aAdHtml);
        echo '<div class="footer_pr">PR</div>' . $aAdHtml[$idx];
    }
