<?php
$aUserInfo = Common::checkLogin();
$sLoginInfo = '<a href="/user/login-input/">ログイン</a>';
if (isset($aUserInfo)) {
    $sLoginInfo = "ようこそ{$aUserInfo['nick_name']}さん <a href=\"/user/\">管理</a>";
}

if (APPLICATION_ENV == 'evaluate') {
    echo '<div style="color:red;font-size:22px;"><br />ここは評価環境です。カードヒーロー@スマホにお越しの方は、下記リンクより通常サイトをご利用下さい。<br /><br /><a style="font-size:22px;" href="http://cardhero-game.net/">カードヒーロー@スマホ 通常サイト</a><br /><br /></div>';
}

$sEnv = '';
switch (APPLICATION_ENV) {
    case 'test_ds_original':
    case 'ds_original':
        $sEnv = 'DSオリジナル';
        break;
    case 'evaluate':
        $sEnv = '評価環境';
        break;
    case 'testing':
        $sEnv = '<span id="test_env">テスト環境</span>';
        break;
}
?>
<div id='header'>
    <div class="title clearfix">
        <div class="h1wrap">
            <h1>
                <img src="/images/cardhero-game.net.jpg" alt="カードヒーロー@スマホ" />
            </h1>
            <div class="env_echo">
                <?php echo $sEnv; ?>
            </div>
        </div>
    </div>
    <div class="links clearfix">
        <div class="top_link">
            <a href="/">メインメニュー</a>
        </div>
        <div class="user_info">
            <?php echo $sLoginInfo . "\n"; ?>
        </div>
    </div>
</div>
<noscript>
    ※Javascriptが無効になっています。
    ブラウザの設定からjavascriptを有効にしてください。
</noscript>
