<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->render('common_head.phtml'); ?>
</head>
<body>
<?php
if (isset($this->layout()->bHideHeader)) {
    echo $this->layout()->content;
    echo $this->render('common_script.phtml');
} else {
    echo $this->render('header.phtml');
    echo $this->layout()->content;
    echo $this->render('common_script.phtml');
    echo $this->render('footer.phtml');
}
?>
</body>
</html>
