<div id="welcome">
    <a href='/card/list/'>
      <div class="card_list">
          <img src="/images/card_list_icon.png" alt="カードリスト" />
          <span>
              カードリスト
          </span>
      </div>
    </a>
    <a href='/game/list/'>
      <div class="field_list">
          <img src="/images/field_list_icon.png" alt="フィールドリスト" />
          <span>
              フィールド一覧
          </span>
      </div>
    </a>
    <a href='/deck/list/'>
      <div class="deck_list">
          <img src="/images/deck_icon.png" alt="デッキ一覧" />
          <span>
              デッキ一覧
          </span>
      </div>
    </a>
    <a href='/game/'>
      <div class="new_game">
          <img src="/images/new_game_icon.png" alt="新規ゲーム開始" />
          <span>
              新規ゲーム開始
          </span>
      </div>
    </a>
</div>
