<?php
$sImageHtml = '';
foreach ($this->aCardInfo['image_info'] as $val) {
        $sImageHtml .= <<<_eos_
    <div class="card_image">
        <img src="{$val['image_file_name']}" width=50 height=50 alt="{$val['card_name']}" />
    </div>

_eos_;
}

$sRareCategory = '★';
$sRareCategory .= $this->aCardInfo['rare'];
$sRareCategory .= '　';
$sRareCategory .= $this->aCardInfo['category_name'];
if (!empty($this->aCardInfo['before_monster_name'])) {
    $sRareCategory .= "　<span class='before_monsters'>{$this->aCardInfo['before_monster_name']}</span>から進化";
}

$sDescription = str_replace('%descstart%', '', $this->aCardInfo['description']);
$sDescription = str_replace('%descend%', '', $sDescription);
if (trim($sDescription) != '') {
    $sDescription = <<<_eos_
    <div class="card_description_frame">
        <div class="label">
            ＜カード紹介＞
        </div>
        <div class="card_description" itemprop="description">
            {$sDescription}
        </div>
    </div>

_eos_;
}
?>
<div id="card_detail_wrapper" itemprop="gameItem" itemscope itemtype="http://schema.org/Game">
    <div class="card_data clearfix">
        <?=$sImageHtml?>
        <div class="card_text">
            <h1 itemprop="name"><?=$this->aCardInfo['card_name']?></h1>
            <div class="card_type">
                <?=$sRareCategory?>
            </div>
            <div class="card_caption"><?=$this->aCardInfo['caption']?></div>
        </div>
    </div>
    <?=$this->render($this->template)?>
    <?=$sDescription?>
</div>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "item": {
            "@id": "/",
            "name": "TOP"
        }
    }, {
        "@type": "ListItem",
        "position": 2,
        "item": {
            "@id": "/card/",
            "name": "カード一覧"
        }
    }, {
        "@type": "ListItem",
        "position": 3,
        "item": {
            "@id": "/card/detail/<?=$this->aCardInfo['card_id']?>/",
            "name": "<?=$this->aCardInfo['card_name']?>"
        }
    }]
}
</script>
