<p class="explain">
    当サイトで使う事ができるカードのリストです。<br />
    DS版カードヒーローのカードをベースにしていますが、効果や性能をアレンジしているカードもあります。<br />
    アレンジされているカードには提案者の名前が表示されています。
</p>
<div class="line_width_adjust"></div>
<?php

foreach ($this->aCardInfo as $val) {
    $sProposer = '';
    if ($val['proposer'] != 'cardhero_ds') {
        $sProposer = $val['proposer'];
    }
    echo <<<_eos_
<div class="card_data card_list_row {$val['category']} clearfix">
    <div class="card_image">
        <img src="/images/card/card.jpg" original-src="{$val['image_file_name']}" width=50 height=50 alt="{$val['card_name']}" />
    </div>
    <div class="card_text">
        <div class="card_name">
            <a href="/card/detail/{$val['card_id']}/">{$val['card_name']}</a>
            　★{$val['rare']}
        </div>
        <div class="card_type">{$val['category_name']}</div>
        <div class="max_lv">{$val['max_lv']}</div>
        <div class="stone_cost">{$val['magic_stone']}</div>
    </div>
    <div class="proposer">
        {$sProposer}
    </div>
</div>

_eos_;
}
?>
<div class="line_width_adjust"></div>
