<h1>カードリスト</h1>
<div id="card_list_wrapper">
<?php
$conf = Zend_Registry::get('config');
?>
<?php if ($conf->web->no_arrange) : ?>
    <p class="explain">
        当サイトで使う事ができるカードのリストです。<br />
        こちらのカードリストは、DS版カードヒーローの物と同一のものになっています。
    </p>
<?php else: ?>
    <p class="explain">
        当サイトで使う事ができるカードのリストです。<br />
        DS版カードヒーローのカードをベースにしていますが、効果や性能をアレンジしているカードもあります。<br />
        アレンジされているカードには、右上に「Arranged」と表示されます。
    </p>
    <div class="narrow_area">
        絞り込み<br />
        アレンジ：
        <select class="arranged_disp_switch">
            <option value="both">すべて表示</option>
            <option value="only_arranged">アレンジのみ表示</option>
            <option value="only_original">アレンジを非表示</option>
        </select><br />
        カードカテゴリ：
        <select class="category_disp_switch">
            <option value="all">すべて表示</option>
            <option value="only_front">前衛のみ表示</option>
            <option value="only_back">後衛のみ表示</option>
            <option value="only_magic">マジックのみ表示</option>
            <option value="only_super">スーパーのみ表示</option>
        </select><br />
    </div>
<?php endif; ?>
    <div class="line_width_adjust"></div>
<?php

foreach ($this->aCardInfo as $val) {
    $sArrangedClass = 'original';
    $sProposer = '';
    if ($val['proposer'] != '') {
        $sArrangedClass = 'arranged';
        $sProposer = 'Arranged';
    }
    if (strpos($val['category'], 'super_') !== FALSE) {
        $val['category'] .= ' super';
    }
    echo <<<_eos_
    <div class="card_data card_list_row {$val['category']} clearfix {$sArrangedClass}">
        <div class="card_image">
            <img src="/images/card/card.jpg" original-src="{$val['image_file_name']}" width=50 height=50 alt="{$val['card_name']}" />
        </div>
        <div class="card_text">
            <div class="card_name">
                <a class="blank_link" href="/card/detail/{$val['card_id']}/" target="_blank">{$val['card_name']}</a>
                　★{$val['rare']}
            </div>
            <div class="card_type">{$val['category_name']}</div>
            <div class="max_lv">{$val['max_lv']}</div>
            <div class="stone_cost">{$val['magic_stone']}</div>
        </div>
        <div class="proposer">
            {$sProposer}
        </div>
    </div>

_eos_;
}
?>
</div>
