<?php
    $aCardInfo = $this->aCardInfoInField;

    $sPlayers  = '投稿者：'   . $this->escape($aCardInfo['field_info']['nick_name']) . "<br />\n";
    if (1 <= $aCardInfo['field_info']['turn_count']) {
        $sPlayers .= '対戦相手：' . $this->escape($aCardInfo['field_info']['opponent_name']);
    }
    $sExplain ='';

    $aPosId = array(
        0 => array(
            'enemyBack2',
            'enemyPlayersInfo',
            'enemyBack1',
        ),
        1 => array(
            'enemyFront2',
            'enemyMaster',
            'enemyFront1',
        ),
        2 => array(
            'myFront1',
            'myMaster',
            'myFront2',
        ),
        3 => array(
            'myBack1',
            'myPlayersInfo',
            'myBack2',
        ),
    );

    // 手札やセットモンスターなど、自分だけが見れる情報を公開するかどうか
    $bDispMyHiddenInfo = false;
    if (isset($this->bKifu, $this->bFinished) && $this->bKifu && $this->bFinished) {
        $bDispMyHiddenInfo = true;
    }
    if (!empty($this->bMine)) {
        $bDispMyHiddenInfo = true;
    }

    foreach ($aCardInfo['field'] as $val) {
        if (isset($val['next_game_card_id'])) {
            continue;
        }

        switch ($val['position'])
        {
            case 'Front1':
                $sPosCode = '(a)';
                break;
            case 'Front2':
                $sPosCode = '(b)';
                break;
            case 'Back1':
                $sPosCode = '(c)';
                break;
            case 'Back2':
                $sPosCode = '(d)';
                break;
            case 'Master':
                $sPosCode = '(m)';
                break;
        }
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $pos = 'my' . $val['position'];
            $sPosCode = strtoupper($sPosCode);
        } else {
            $pos = 'enemy' . $val['position'];
        }
        $sStandbyClass = '';
        $sCardBack = '';
        if ($val['standby_flg']) {
            $sLv = '?';
            $sHp = '?';
            if ($bDispMyHiddenInfo && $aCardInfo['field_info']['turn'] == $val['owner']) {
                $sStandbyClass = 'standby';
                $sCardBack = "<img src='/images/card/card.jpg' style='display:none;'/>";
            } else {
                $val['image_file_name'] = 'card.jpg';
                $val['card_name'] = 'カードヒーロー';
            }
        } else {
            $sLv = $val['lv'];
            $sHp = $val['hp'];
        }
        $sLvHp  = '<span class="mini-font">LV</span><span class="lv">' . $sLv . '</span>';
        $sLvHp .= '<span class="mini-font">HP</span><span class="hp">' . $sHp . '</span>';

        $sEffect  = '<span class="power"></span>';
        $sEffect .= '<span class="shield"></span>';
        $sEffect .= '<span class="magic"></span>';
        $sEffect .= '<span class="charge"></span>';
        $aEffectFlags = array();
        if (!empty($val['status'])) {
            foreach ($val['status'] as $aStatusVal) {
                switch ($aStatusVal['type']) {
                    case '!':
                        $aEffectFlags['charge'] = true;
                        break;
                    case 'P':
                        $aEffectFlags['power'] = true;
                        break;
                    case 'S':
                        $aEffectFlags['shield'] = true;
                        break;
                    case 'M':
                        $aEffectFlags['magic'] = true;
                        break;
                }
                if (isset($aStatusVal['explain']) && $aStatusVal['explain'] != '') {
                    $sExplain .= $this->escape($aStatusVal['explain']) . "<br />\n";
                }
            }
        }
        if (isset($aEffectFlags['charge'])) {
            $sEffect = str_replace('"charge">', '"charge">！', $sEffect);
        }
        if (isset($aEffectFlags['power'])) {
            $sEffect = str_replace('"power">', '"power">P', $sEffect);
        }
        if (isset($aEffectFlags['shield'])) {
            $sEffect = str_replace('"shield">', '"shield">S', $sEffect);
        }
        if (isset($aEffectFlags['magic'])) {
            $sEffect = str_replace('"magic">', '"magic">M', $sEffect);
        }
        $aMonsterData[$pos] = <<<_eos_
        <td pos_id="{$pos}" monster_id="{$val['monster_id']}">
            <div class="pos_id">
                <span class="mini-font">{$sPosCode}</span>
            </div>
            <div class="pict {$sStandbyClass}">
                <img src="/images/card/card.jpg" original-src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
                {$sCardBack}
            </div>
            <div class="param">
                {$sLvHp}
            </div>
            <div class="param">
                {$sEffect}
            </div>
        </td>

_eos_;
    }

    $sMyHandHtml = '';
    $aHandCount = array(
        'my'    => 0,
        'enemy' => 0,
    );
    foreach ($aCardInfo['hand'] as $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $aHandCount['my']++;
            $sOriginalSource = '';
            if ($bDispMyHiddenInfo) {
                $sOriginalSource = " original-src='/images/card/{$val['image_file_name']}'";
            }
            $sMyHandHtml .= <<<_eos_
        <img src="/images/card/card.jpg" {$sOriginalSource} alt=""/>

_eos_;
        } else {
            $aHandCount['enemy']++;
        }
    }

    if ($aCardInfo['field_info']['turn'] == 1) {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone1'],
            'enemy' => $aCardInfo['field_info']['stone2'],
        );
    } else {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone2'],
            'enemy' => $aCardInfo['field_info']['stone1'],
        );
    }
    $aMonsterData['enemyPlayersInfo'] = <<<_eos_
        <td class="players_info">
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['enemy']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['enemy']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;
    $aMonsterData['myPlayersInfo'] = <<<_eos_
        <td class="players_info">
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['my']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['my']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;

$sClass = 'game_row';
if (!empty($aCardInfo['field_info']['responced'])) {
    $sClass .= ' res';
}
$aUserInfo = $this->aUserInfo;
if (isset($aCardInfo['field_info']['user_id']) && $aCardInfo['field_info']['user_id'] == $aUserInfo['user_id']) {
    $sClass .= ' mine';
}
if (isset($aCardInfo['field_info']['opponent_id']) && $aCardInfo['field_info']['opponent_id'] == $aUserInfo['user_id']) {
    $sClass .= ' wait_for_me';
}

echo <<<_eos_
<div class="{$sClass}">
    <table class="game_field">

_eos_;

$iGameFieldId = $aCardInfo['field_info']['game_field_id'];
foreach ($aPosId as $i => $aLine) {
    echo "        <tr>\n";
    foreach ($aLine as $posId) {
        if (!isset($aMonsterData[$posId])) {
            $aMonsterData[$posId] = "            <td pos_id=\"{$posId}\"><div class=\"pict\"></div></td>\n";
        }
        echo $aMonsterData[$posId];
    }
    if ($i == 0) {
        $sButtonHtml = '';
        if (empty($this->bGameStart)) {
            $sUrl = "/game/field/{$iGameFieldId}/";
            if (!empty($this->bLast)) {
                $sUrl .= '?referer=last';
            } else if (!empty($this->bMine)) {
                $sUrl .= '?referer=myturn';
            }
            $sLabel = 'このフィールドで遊ぶ';
            if (!empty($this->bKifu)) {
                $sLabel = 'このフィールドを詳しく見る';
            } else if (!empty($this->bFinisher)) {
                $sLabel = 'このフィールドを詳しく見る';
            }
            $sButtonHtml .= "<a href='{$sUrl}'><div class='button game_play'>{$sLabel}</div></a>";
            if (empty($this->bKifu) && 1 <= $aCardInfo['field_info']['turn_count']) {
                $sUrl = "/game/kifu/{$iGameFieldId}/";
                $sButtonHtml .= "<a href='{$sUrl}'><div class='button view_log' game_field_id='{$iGameFieldId}'>プレイログを見る</div></a>";
            }
        }

        if (!empty($aCardInfo['field_info']['finished_flg'])) {
            $sUrl = "/game/replay/{$iGameFieldId}/";
            $sButtonHtml .= "<a href='{$sUrl}'><div class='button movie_replay' game_field_id='{$iGameFieldId}'>再現ムービーを見る</div></a>";
        }

        echo <<<_eos_
            <td colspan="3" rowspan="4" class="explain">
                <div class="player_name">
                    {$sPlayers}
                </div>
                <div class="magic_effects">
                    {$sExplain}
                </div>
                {$sButtonHtml}
            </td>

_eos_;
    }
    echo "        </tr>\n";
}
    echo <<<_eos_
    </table>
    <div class="hand_card">
{$sMyHandHtml}
    </div>
</div>

_eos_;

