<div class="message">
<?php
    if (isset($this->sDispMessage)) {
        echo $this->sDispMessage;
    }
?>
</div>
<div class="edit_link">
    <a href="/deck/edit/">デッキ新規作成</a>
</div>
<?php
$aUserInfo = Common::checkLogin();
foreach ($this->aDeckList as $deckId => $val) {
    $sEditLink = '';
    if ($val['owner_id'] != null && $val['owner_id'] == $aUserInfo['user_id']) {
        $sEditLink = <<<_eos_
    <div class="edit_link mine">
        <a href="/deck/edit/{$deckId}/">デッキ編集</a>
    </div>

_eos_;
    }
    $sCardListHtml = '';
    foreach ($val['cards'] as $listCard) {
        for ($i = 0 ; $i < $listCard['num'] ; $i++)
        $sCardListHtml .= <<<_eos_
        <img src="/images/card/{$listCard['image_file_name']}" alt="{$listCard['card_name']}" />

_eos_;
    }
    foreach ($val as $key => $v) {
        if (!is_array($v)) {
            $val[$key] = $this->escape($v);
        }
    }
    echo <<<_eos_
<div class="deck_frame">
    <div class="deck_header clearfix">
        <div class="master_image">
            <img src="/images/card/{$val['master_image']}" alt="{$val['master_card_name']}" />
        </div>
        <div class="deck_summary">
            <div class="title">{$val['deck_name']}</div>
            <div class="owner">投稿者：{$val['owner_nick_name']}</div>
            <div class="struct">
                合計レアリティ:★<span class="rare_sum_num">{$val['rare_sum']}</span>
                最大レアリティ:★<span class="rare_max_num">{$val['rare_max']}</span><br />
                <!--
                デッキ枚数:<span class="deck_cards_num">{$val['deck_cards_num']}</span>枚
                -->
                前衛:<span class="front_cards_num">{$val['front_cards_num']}</span>枚
                後衛:<span class="back_cards_num">{$val['back_cards_num']}</span>枚
                マジック:<span class="magic_cards_num">{$val['magic_cards_num']}</span>枚
                スーパー:<span class="super_cards_num">{$val['super_cards_num']}</span>枚
            </div>
        </div>
    </div>
    <div class="card_list">
{$sCardListHtml}
    </div>
{$sEditLink}
</div>

_eos_;
}
?>
<div class="edit_link">
    <a href="/deck/edit/">デッキ新規作成</a>
</div>
