<?php
    $aCardInfo = $this->aCardInfo;

    $aPosId = array(
        0 => array(
            'enemyBack2',
            'enemyPlayersInfo',
            'enemyBack1',
        ),
        1 => array(
            'enemyFront2',
            'enemyMaster',
            'enemyFront1',
        ),
        2 => array(
            'myFront1',
            'myMaster',
            'myFront2',
        ),
        3 => array(
            'myBack1',
            'myPlayersInfo',
            'myBack2',
        ),
    );
    foreach ($aCardInfo['field'] as $iGameCardId => $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $pos = 'my' . $val['position'];
        } else {
            $pos = 'enemy' . $val['position'];
        }

        $sStatusDetail = '';
        if ($val['standby_flg']) {
            $sLv = '?';
            $sHp = '?';
            $sStatusDetail .= '<div standby_flg=1></div>';
        } else {
            $sLv = $val['lv'];
            $sHp = $val['hp'];
        }
        $sLvHp  = '<span class="mini-font">LV</span><span class="lv">' . $sLv . '</span>';
        $sLvHp .= '<span class="mini-font">HP</span><span class="hp">' . $sHp . '</span>';

        $sEffect  = '<span class="power"></span>';
        $sEffect .= '<span class="shield"></span>';
        $sEffect .= '<span class="magic"></span>';
        $sEffect .= '<span class="charge"></span>';
        $aEffectFlags = array();
        if (isset($val['status']) && $val['status'] != '') {
            foreach ($val['status'] as $aStatusVal) {
                switch ($aStatusVal['type']) {
                    case '!':
                        $aEffectFlags['charge'] = true;
                        break;
                    case 'P':
                        $aEffectFlags['power'] = true;
                        break;
                    case 'S':
                        $aEffectFlags['shield'] = true;
                        break;
                    case 'M':
                        $aEffectFlags['magic'] = true;
                        break;
                }
                $sStatusDetail .= <<<_eos_
                    <div class="status_row"
                        status_id="{$aStatusVal['id']}"
                        turn_count="{$aStatusVal['turn']}"
                        param1="{$aStatusVal['param1']}"
                        param2="{$aStatusVal['param2']}"></div>

_eos_;
            }
        }
        if (isset($aEffectFlags['charge'])) {
            $sEffect = str_replace('"charge">', '"charge">！', $sEffect);
        }
        if (isset($aEffectFlags['power'])) {
            $sEffect = str_replace('"power">', '"power">P', $sEffect);
        }
        if (isset($aEffectFlags['shield'])) {
            $sEffect = str_replace('"shield">', '"shield">S', $sEffect);
        }
        if (isset($aEffectFlags['magic'])) {
            $sEffect = str_replace('"magic">', '"magic">M', $sEffect);
        }
        $aMonsterData[$pos] = <<<_eos_
        <td id="{$pos}" class="monster_space" monster_id="{$val['monster_id']}" card_id="{$val['card_id']}" game_card_id="{$iGameCardId}">
            <div class="pict">
                <img src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
            </div>
            <div class="param">
                {$sLvHp}
            </div>
            <div class="param">
                {$sEffect}
                <div class="status_hidden_param" style="display:none;">
                    {$sStatusDetail}
                </div>
            </div>
        </td>

_eos_;
    }

    $sMyHandHtml = '';
    $sHandCards = '';
    $aHandCount = array(
        'my'    => 0,
        'enemy' => 0,
    );
    foreach ($this->aCardInfo['hand'] as $iGameCardId => $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $aHandCount['my']++;
            $sMyHandHtml .= <<<_eos_
    <div class="hand_card" game_card_id="{$iGameCardId}" card_id="{$val['card_id']}">
        <img src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
    </div>

_eos_;
        } else {
            $aHandCount['enemy']++;
        }
        $sHandCards .= <<<_eos_
<div class="hand_card"
    game_card_id="{$iGameCardId}"
    card_id="{$val['card_id']}"
    owner="{$val['owner']}" ></div>

_eos_;
    }

    if ($aCardInfo['field_info']['turn'] == 1) {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone1'],
            'enemy' => $aCardInfo['field_info']['stone2'],
        );
    } else {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone2'],
            'enemy' => $aCardInfo['field_info']['stone1'],
        );
    }
    $aMonsterData['enemyPlayersInfo'] = <<<_eos_
        <td id="enemyPlayersInfo">
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['enemy']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['enemy']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;
    $aMonsterData['myPlayersInfo'] = <<<_eos_
        <td id="myPlayersInfo">
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['my']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['my']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;

    $sDeckCards = '';
    if (isset($aCardInfo['deck']) && $aCardInfo['deck'] != '') {
        foreach ($aCardInfo['deck'] as $iGameCardId => $val) {
            $sDeckCards .= <<<_eos_
<div class="deck_card"
    game_card_id="{$iGameCardId}"
    card_id="{$val['card_id']}"
    owner="{$val['owner']}" ></div>

_eos_;
        }
    }

    $sUsedCards = '';
    if (isset($aCardInfo['used']) && $aCardInfo['used'] != '') {
        foreach ($aCardInfo['used'] as $iGameCardId => $val) {
            $sUsedCards .= <<<_eos_
<div class="used_card"
    game_card_id="{$iGameCardId}"
    card_id="{$val['card_id']}"
    owner="{$val['owner']}" ></div>

_eos_;
        }
    }
?>
<table id="game_field">
<?php
    foreach ($aPosId as $aLine) {
        echo "    <tr>\n";
        foreach ($aLine as $posId) {
            if (!isset($aMonsterData[$posId])) {
                $aMonsterData[$posId] = "        <td id='{$posId}' class='monster_space'><div class='pict'></div></td>\n";
            }
            echo $aMonsterData[$posId];
        }
        echo "    </tr>\n";
    }
?>
</table>
<div id="hand_card" class="clearfix">
<?php echo $sMyHandHtml; ?>
</div>
<div id="card_info">
    <div id="card_info_frame">
        <div class="card_info_title">
            Card Infomation
        </div>
        <div class="card_summary clearfix">
            <div class="card_image"></div>
            <div class="card_name"></div>
            <div class="dtl_link"></div>
        </div>
        <div class="act_commands">
        </div>
    </div>
</div>
<div id="buttons_frame">
    <div class="cancel_button">
        キャンセル
    </div>
    <div class="turn_end_button">
        ターンエンド
    </div>
</div>

<div class="hidden_cards_info" style="display:none;">
<?php
    echo $sHandCards;
    echo $sDeckCards;
    echo $sUsedCards;
    echo '<div turn_num="' . $aCardInfo['field_info']['turn'] . '"></div>';
?>
</div>

