<?php
    $aCardInfo = $this->aCardInfo;

    $aPosId = array(
        0 => array(
            'enemyBack2',
            'enemyPlayersInfo',
            'enemyBack1',
        ),
        1 => array(
            'enemyFront2',
            'enemyMaster',
            'enemyFront1',
        ),
        2 => array(
            'myFront1',
            'myMaster',
            'myFront2',
        ),
        3 => array(
            'myBack1',
            'myPlayersInfo',
            'myBack2',
        ),
    );
    foreach ($aCardInfo['field'] as $iGameCardId => $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $pos = 'my' . $val['position'];
        } else {
            $pos = 'enemy' . $val['position'];
        }
        if ($val['standby_flg']) {
            $sLv = '?';
            $sHp = '?';
        } else {
            $sLv = $val['lv'];
            $sHp = $val['hp'];
        }
        $sLvHp  = '<span class="mini-font">LV</span><span class="lv">' . $sLv . '</span>';
        $sLvHp .= '<span class="mini-font">HP</span><span class="hp">' . $sHp . '</span>';

        $sStatusDetail = '';
        $sEffect  = '<span class="power"></span>';
        $sEffect .= '<span class="shield"></span>';
        $sEffect .= '<span class="magic"></span>';
        $sEffect .= '<span class="charge"></span>';
        if (isset($val['status']) && $val['status'] != '') {
            foreach ($val['status'] as $aStatusVal) {
                switch ($aStatusVal['type']) {
                    case '!':
                        $sEffect = str_replace('"charge">', '"charge">！', $sEffect);
                        break;
                    case 'P':
                        $sEffect = str_replace('"power">', '"power">P', $sEffect);
                        break;
                    case 'S':
                        $sEffect = str_replace('"shield">', '"shield">S', $sEffect);
                        break;
                    case 'M':
                        $sEffect = str_replace('"magic">', '"magic">M', $sEffect);
                        break;
                }
            }
        }
        $aMonsterData[$pos] = <<<_eos_
        <td id="{$pos}" monster_id="{$val['monster_id']}" game_card_id="{$iGameCardId}">
            <div class="pict">
                <img src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
            </div>
            <div class="param">
                {$sLvHp}
            </div>
            <div class="param">
                {$sEffect}
                <div class="status_hidden_param" style="display:none;">
                    {$sStatusDetail}
                </div>
            </div>
        </td>

_eos_;
    }

    $sMyHandHtml = '';
    $aHandCount = array(
        'my'    => 0,
        'enemy' => 0,
    );
    foreach ($this->aCardInfo['hand'] as $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $aHandCount['my']++;
            $sMyHandHtml .= <<<_eos_
    <div>
        <img src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}" card_id="{$val['card_id']}"/>
    </div>

_eos_;
        } else {
            $aHandCount['enemy']++;
        }
    }

    if ($aCardInfo['field_info']['turn'] == 1) {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone1'],
            'enemy' => $aCardInfo['field_info']['stone2'],
        );
    } else {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone2'],
            'enemy' => $aCardInfo['field_info']['stone1'],
        );
    }
    $aMonsterData['enemyPlayersInfo'] = <<<_eos_
        <td>
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['enemy']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['enemy']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;
    $aMonsterData['myPlayersInfo'] = <<<_eos_
        <td>
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['my']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['my']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;
?>
<table id="game_field">
<?php
    foreach ($aPosId as $aLine) {
        echo "    <tr>\n";
        foreach ($aLine as $posId) {
            if (!isset($aMonsterData[$posId])) {
                $aMonsterData[$posId] = "        <td id='{$posId}'><div class='pict'></div></td>\n";
            }
            echo $aMonsterData[$posId];
        }
        echo "    </tr>\n";
    }
?>
</table>
<div id="hand_card" class="clearfix">
<?php echo $sMyHandHtml; ?>
</div>
<div id="card_info">
    <div id="card_info_frame">
        <div class="card_info_title">
            Card Infomation
        </div>
        <div class="card_summary clearfix">
            <div class="card_image"></div>
            <div class="card_name"></div>
            <div class="dtl_link"></div>
        </div>
        <div class="act_commands">
        </div>
    </div>
</div>
<div id="buttons_frame">
    <div class="cancel_button">
        キャンセル
    </div>
    <div class="turn_end_button">
        ターンエンド
    </div>
</div>

