<?php
    $aCardInfo = $this->aCardInfo;

    $aPosId = array(
        0 => array(
            'enemyBack2',
            'enemyPlayersInfo',
            'enemyBack1',
        ),
        1 => array(
            'enemyFront2',
            'enemyMaster',
            'enemyFront1',
        ),
        2 => array(
            'myFront1',
            'myMaster',
            'myFront2',
        ),
        3 => array(
            'myBack1',
            'myPlayersInfo',
            'myBack2',
        ),
    );
    foreach ($aCardInfo['field'] as $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $pos = 'my' . $val['position'];
        } else {
            $pos = 'enemy' . $val['position'];
        }
        $sLvLabel = 'LV';
        $sLv = $val['lv'];
        if ($val['category'] == 'master') {
            $sLvLabel = 'S';
            if ($val['owner'] == 1) {
                $sLv = $aCardInfo['field_info']['stone1'];
            } else {
                $sLv = $aCardInfo['field_info']['stone2'];
            }
        }
        $sHp = $val['hp'];
        $sEffect  = '<span class="power"></span>';
        $sEffect .= '<span class="shield"></span>';
        $sEffect .= '<span class="magic"></span>';
        $sEffect .= '<span class="charge"></span>';
        if (isset($val['power_effect']) && $val['power_effect'] != '') {
            $sEffect = str_replace('"power">', '"power">P', $sEffect);
        }
        if (isset($val['shield_effect']) && $val['shield_effect'] != '') {
            $sEffect = str_replace('"shield">', '"shield">S', $sEffect);
        }
        if (isset($val['magic_effect']) && $val['magic_effect'] != '') {
            $sEffect = str_replace('"magic">', '"magic">M', $sEffect);
        }
        if (isset($val['charge']) && $val['charge']) {
            $sEffect = str_replace('"charge">', '"charge">！', $sEffect);
        }
        $aMonsterData[$pos] = <<<_eos_
        <td id="{$pos}" monster_id="{$val['monster_id']}">
            <div class="pict">
                <img src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
            </div>
            <div class="param">
                <span class="mini-font">{$sLvLabel}</span><span class="lv">{$sLv}</span>
                <span class="mini-font">HP</span><span class="hp">{$sHp}</span>
            </div>
            <div class="param">
                {$sEffect}
            </div>
        </td>

_eos_;
    }
    $aMonsterData['enemyPlayersInfo'] = <<<_eos_
        <td>
            <div class="num_info stone">
            </div>
            <div class="num_info hand">
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;
    $aMonsterData['myPlayersInfo'] = <<<_eos_
        <td>
            <div class="num_info stone">
            </div>
            <div class="num_info hand">
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;
?>
<table id="game_field">
<?php
    foreach ($aPosId as $aLine) {
        echo "    <tr>\n";
        foreach ($aLine as $posId) {
            if (!isset($aMonsterData[$posId])) {
                $aMonsterData[$posId] = "        <td id='{$posId}'><div class='pict'></div></td>\n";
            }
            echo $aMonsterData[$posId];
        }
        echo "    </tr>\n";
    }
?>
</table>
<div id="hand_card" class="clearfix">
<?php
    foreach ($aCardInfo['hand'] as $val) {
        echo <<<_eos_
    <div>
        <img src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}" card_id="{$val['card_id']}"/>
    </div>

_eos_;
    }
?>
</div>
<div id="card_info">
    <div id="card_info_frame">
        <div class="card_info_title">
            Card Infomation
        </div>
        <div class="card_summary clearfix">
            <div class="card_image"></div>
            <div class="card_name"></div>
            <div class="dtl_link"></div>
        </div>
        <div class="act_commands">
            <div class="command_row">
            </div>
        </div>
    </div>
</div>
<div id="buttons_frame">
    <div class="cancel_button">
        キャンセル
    </div>
</div>

