<div id="welcome">
    <h1>カードヒーロー＠スマホ へようこそ！</h1>
    <div id="what_is_this">
        <p>
        <?php echo nl2br($this->sExplain); ?>
        </p>
    </div>
    <div id="panel_frame" class="clearfix">
        <a href='/card/'>
          <div class="card_list">
              <img src="/images/card_list_icon.png" alt="カードリスト" />
              <span>
                  カードリスト
              </span>
          </div>
        </a>
        <a href='/game/'>
          <div class="field_list">
              <img src="/images/field_list_icon.png" alt="フィールドリスト" />
              <span>
                  フィールド一覧
              </span>
          </div>
        </a>
        <a href='/deck/'>
          <div class="deck_list">
              <img src="/images/deck_icon.png" alt="デッキ一覧" />
              <span>
                  デッキ一覧
              </span>
          </div>
        </a>
        <a href='/game/new/'>
          <div class="new_game">
              <img src="/images/new_game_icon.png" alt="新規ゲーム開始" />
              <span>
                  新規ゲーム開始
              </span>
          </div>
        </a>
    </div>
    <div id="update_history">
        <h2>更新履歴・お知らせ</h2>
        <div>
            <ul>
                <li>[2015/03/01]マリガン機能を追加。これに伴い、ゲーム開始手順が一部変更されます。</li>
                <li class="important">[2015/02/28]レオン・ラオン・ダイン・シグマ・オクトロスのカード性能を下方修正</li>
                <li>[2015/02/15]自分のデッキのみの一覧を追加。ログインした状態でのみ利用できます。</li>
                <li>[2015/02/07]カードリストに絞り込み機能を追加し、別ウィンドウでカード詳細画面へ遷移するよう変更。また変更されたカードについて、変更者名を出さないよう変更</li>
                <li>[2015/02/05]トップページ更新履歴欄にて、事前お知らせを掲載できるよう改修</li>
                <li>[2015/01/29]トップページにサイト紹介文を掲載</li>
                <li>[2015/01/21]未返信フィールド一覧・棋譜一覧を追加</li>
                <li class="important">[2015/01/16]先攻ドロー及び２行動・３行動モンスターの気合だめコマンドを廃止。またシトラスのアシストでレベルが１しか上がらないよう変更</li>
                <li>[2015/01/12]手札調整機能を追加</li>
                <li>[2015/01/06]デッキ一覧に「もっと見る」ボタンを追加</li>
                <li>[2014/12/08]PCでアクセスした際にも操作しやすいよう、デザインの改善</li>
                <li>[2014/11/22]フィールド詳細画面にて、直前の相手ターンの行動を再現する機能を追加</li>
                <li>[2014/11/08]返信済みフィールドの表示切り替え機能を追加</li>
                <li class="important">[2014/10/29]フィールド投稿機能完成！</li>
                <li class="important">[2014/05/24]サイトオープン！</li>
            </ul>
            <a class="more" href="javascript:void(0);">全部見る</a>
        </div>
    </div>
    <div id="outbound_links">
        <h2>カードヒーロー　関連リンク</h2>
        <ul>
            <li><a class="blank_link" target="_blank" href="http://www.nintendo.co.jp/n02/dmg/ahhj/">カードヒーローBGC版　公式サイト</a></li>
            <li><a class="blank_link" target="_blank" href="http://www.nintendo.co.jp/ds/ychj/">カードヒーローDS版　公式サイト</a></li>
            <li><a class="blank_link" target="_blank" href="http://www.cardhero-bu.com/">カードヒーロー部.com</a></li>
        </ul>
    </div>
</div>
