<?php
$aSisterSite = array(
    'production' => array(
        'url'   => '//cardhero-game.net/',
        'title' => 'カードヒーロー＠スマホ カードセット',
    ),
    'ds_original' => array(
        'url'   => '//ds-original.cardhero-game.net/',
        'title' => 'DS版オリジナルカードセット',
    ),
);
$sSisterSite = '';
foreach ($aSisterSite as $key => $val) {
    if ($key == APPLICATION_ENV) {
        $sSisterSite .= "<li>{$val['title']}</li>\n";
    } else {
        $sSisterSite .= "<li><a href='{$val['url']}' target='_top'>{$val['title']}</a></li>\n";
    }
}

$sPanelHtml = '';
foreach ($this->aPanelInfo as $key => $val) {
    $sPanelHtml .= <<<_eos_
            <a href="{$val['url']}" target="_top">
              <div class="{$val['class']}">
                  <img src="/images/{$val['img']}" alt="{$val['alt']}" />
                  <span>{$val['text']}</span>
              </div>
            </a>

_eos_;
}
?>
<style>
#lightbox_mainmenu .main_column {
    float: initial;
    margin: auto;
}
#lightbox_mainmenu .main_column #panel_frame {
    min-width: 320px;
}
#lightbox_mainmenu .main_column #panel_frame div {
    background-color: white;
}
</style>
<div id="lightbox_mainmenu">
    <div class="main_column">
        <div id="panel_frame" class="clearfix">
            <?=$sPanelHtml?>
            <a href="/" target="_top">
              <div class="top_page">
                  <img src="/images/favicon.ico" alt="トップページ" />
                  <span>トップページ</span>
              </div>
            </a>
        </div>
    </div>
    <div class="bottom_column clearfix">
        <div id="outbound_links">
            <h2>カードヒーロー　関連リンク</h2>
            <ul>
                <li><a class="blank_link" target="_blank" href="http://www.nintendo.co.jp/n02/dmg/ahhj/">カードヒーローBGC版　公式サイト</a></li>
                <li><a class="blank_link" target="_blank" href="http://www.nintendo.co.jp/ds/ychj/">カードヒーローDS版　公式サイト</a></li>
                <li><a class="blank_link" target="_blank" href="http://www.cardhero-bu.com/">カードヒーロー部.com</a></li>
            </ul>
            <h2>カードヒーロー＠スマホ カードセットバリエーション</h2>
            <ul>
                <?=$sSisterSite?>
            </ul>
        </div>
    </div>
</div>
