<html>
<head>
<meta name="viewport" content="width=device-width,user-scalable=yes,initial-scale=1,minimum-scale=1" />
<style>
p {
    text-align: center;
    margin: 15px;
}

textarea {
    width: 90%;
    height: 400px;
    margin: auto;
    display: block;
}
</style>
</head>
<body>
<form name="form1" method="post">
<p>
<input type="submit" value="SAVE" />
</p>
<br />
<textarea name="memo">
<?php
if (isset($_POST) && isset($_POST['memo'])) {
    file_put_contents('/var/www/vhosts/memo.txt', $_POST['memo']);
}
echo file_get_contents('/var/www/vhosts/memo.txt');
?>
</textarea>
<br />
<p>
<input type="submit" value="SAVE" />
</p>
</form>
</body>
</html>
