<?php
$conf = Zend_Registry::get('config');
?>
<div id="error_content">
    <h1>エラー</h1>
    <h2><?php echo $this->message ?></h2>

    <?php if ($conf->phpSettings->display_errors && isset($this->exception)): ?>

    <h3>Exception information:</h3>
    <p>
        <b>Errors Type:</b> <?php echo $this->errorType; ?>
    </p>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <div style="width:100%; min-height:100px; background-color:#eeffff; overflow:scroll;">
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>
    </div>

    <h3>Request Parameters:</h3>
    <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
    </pre>

    <?php endif ?>
</div>
