<?php
$conf = Zend_Registry::get('config');
$url = 'https://twitter.com/gittib_gittib/timelines/704334380739592192';
$sExp = <<<_eos_
すみませんが、もうしばらくお待ち下さい。
「聞いてないよ！」という方は、お手数ですが<a href="{$url}">twitterの更新情報フィード</a>をご確認願います。（更新してなかったらごめんなさい）

_eos_;
?>
<style>
#maintenance h1 {
    font-size: 1.4em;
}
#maintenance p {
    margin: 15px;
}
</style>
<div id="maintenance">
    <h1>ただ今、サーバーメンテナンス中です。</h1>
    <p><?= nl2br($sExp) ?></p>
</div>
