<?php
foreach ($this->aCardInfoArray as $aCardInfo) {
    
    $sExplain ='';
    $sExplain ='あいうえおかきくけこさしすせそたちつてとあいうえおかきくけこさしすせそたちつてと';

    $aPosId = array(
        0 => array(
            'enemyBack2',
            'enemyPlayersInfo',
            'enemyBack1',
        ),
        1 => array(
            'enemyFront2',
            'enemyMaster',
            'enemyFront1',
        ),
        2 => array(
            'myFront1',
            'myMaster',
            'myFront2',
        ),
        3 => array(
            'myBack1',
            'myPlayersInfo',
            'myBack2',
        ),
    );
    foreach ($aCardInfo['field'] as $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $pos = 'my' . $val['position'];
        } else {
            $pos = 'enemy' . $val['position'];
        }
        if ($val['standby_flg']) {
            $sLv = '?';
            $sHp = '?';
        } else {
            $sLv = $val['lv'];
            $sHp = $val['hp'];
        }
        $sEffect  = '<span class="power"></span>';
        $sEffect .= '<span class="shield"></span>';
        $sEffect .= '<span class="magic"></span>';
        $sEffect .= '<span class="charge"></span>';
        if (isset($val['status']) && $val['status'] != '') {
            foreach ($val['status'] as $aStatusVal) {
                switch ($aStatusVal['type']) {
                    case '!':
                        $sEffect = str_replace('"charge">', '"charge">！', $sEffect);
                        break;
                    case 'P':
                        $sEffect = str_replace('"power">', '"power">P', $sEffect);
                        break;
                    case 'S':
                        $sEffect = str_replace('"shield">', '"shield">S', $sEffect);
                        break;
                    case 'M':
                        $sEffect = str_replace('"magic">', '"magic">M', $sEffect);
                        break;
                }
            }
        }
        $aMonsterData[$pos] = <<<_eos_
        <td pos_id="{$pos}" monster_id="{$val['monster_id']}">
            <div class="pict">
                <img src="/images/card/card.jpg" original-src="/images/card/{$val['image_file_name']}" alt="{$val['card_name']}"/>
            </div>
            <div class="param">
                <span class="mini-font">LV</span><span class="lv">{$sLv}</span><span class="mini-font">HP</span><span class="hp">{$sHp}</span>
            </div>
            <div class="param">
                {$sEffect}
            </div>
        </td>

_eos_;
    }

    $sMyHandHtml = '';
    $aHandCount = array(
        'my'    => 0,
        'enemy' => 0,
    );
    foreach ($aCardInfo['hand'] as $val) {
        if ($aCardInfo['field_info']['turn'] == $val['owner']) {
            $aHandCount['my']++;
            $sMyHandHtml .= <<<_eos_
        <img src="/images/card/card.jpg" alt=""/>

_eos_;
        } else {
            $aHandCount['enemy']++;
        }
    }

    if ($aCardInfo['field_info']['turn'] == 1) {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone1'],
            'enemy' => $aCardInfo['field_info']['stone2'],
        );
    } else {
        $aStoneCount = array(
            'my'    => $aCardInfo['field_info']['stone2'],
            'enemy' => $aCardInfo['field_info']['stone1'],
        );
    }
    $aMonsterData['enemyPlayersInfo'] = <<<_eos_
        <td>
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['enemy']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['enemy']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;
    $aMonsterData['myPlayersInfo'] = <<<_eos_
        <td>
            <div class="num_info stone">
                <img src="/images/stone.png" alt="stone" />：
                <span>{$aStoneCount['my']}</span>
            </div>
            <div class="num_info hand">
                <img src="/images/card/card.jpg" alt="hand" />：
                <span>{$aHandCount['my']}</span>
            </div>
            <div class="num_info deck">
            </div>
            <div class="num_info used">
            </div>
        </td>

_eos_;

echo <<<_eos_
<div href="/game/field/{$aCardInfo['field_info']['game_field_id']}/" class="game_row">
    <table class="game_field">

_eos_;
foreach ($aPosId as $i => $aLine) {
    echo "        <tr>\n";
    foreach ($aLine as $posId) {
        if (!isset($aMonsterData[$posId])) {
            $aMonsterData[$posId] = "            <td pos_id=\"{$posId}\"><div class=\"pict\"></div></td>\n";
        }
        echo $aMonsterData[$posId];
    }
    if ($i == 0) {
        echo "            <td colspan=3 rowspan=4 class=\"explain\">{$sExplain}</td>\n";
    }
    echo "        </tr>\n";
}
    echo <<<_eos_
    </table>
    <div class="hand_card">
{$sMyHandHtml}
    </div>
</div>

_eos_;
}
