<?php
$sAdContents = '';
foreach ($this->aAd as $iAdId => $val) {
    $sTrClass = '';
    if ($val['del_flg']) {
        $sTrClass .= ' hide ';
    }
    if ($val['start_date'] <= date('Y-m-d H:i') && date('Y-m-d H:i') <= $val['end_date']) {}
    else {
        $sTrClass .= ' term_over ';
    }
    if (empty($val['ad_comment'])) {
        $val['ad_comment'] = 'コメント無し';
    }

    $sCode = $this->escape($val['code']);
    $sStart = date('Y-m-d H:i', strtotime($val['start_date']));
    $sEnd = date('Y-m-d H:i', strtotime($val['end_date']));
    $sAdContents .= <<<_eos_
        <tr class="{$sTrClass}">
            <td><a href="/admin/ad/?ad_group_id={$val['ad_group_id']}">{$val['ad_group_id']}</a></td>
            <td>{$val['ad_id']}</td>
            <td>{$val['ad_type']}</td>
            <td class="comment"><a href='/admin/ad/edit/?ad_id={$val['ad_id']}' target='_blank'>{$val['ad_comment']}</a></td>
            <td class="term from">{$sStart}</td>
            <td class="term to">{$sEnd}</td>
        </tr>

_eos_;
}
?>
<div id="admin_ad">
    <h1>広告管理画面</h1>
    <div class="scroll_frame">
        <label>
            <input type="checkbox" id="hide_old_ad" />終了広告非表示
        </label>
        <table id="ad_list" cellspacing=0>
            <tr>
                <th>GROUP</th>
                <th>ID</th>
                <th>タイプ</th>
                <th>コメント</th>
                <th class="term from">開始日時</th>
                <th class="term to">終了日時</th>
            </tr>
            <?php echo $sAdContents; ?>
        </table>
    </div>
    <a id="add_new_ad" href="/admin/ad/add-ad/" target="_blank">新規広告追加</a>
</div>
