<div id="ranking_index">
    <h1>＠スマホ　ランキング</h1>
    <div class="crowns">
        <img src="/images/ranking/crown1.png" alt="gold" />
        <img src="/images/ranking/crown2.png" alt="silver" />
        <img src="/images/ranking/crown3.png" alt="bronze" />
    </div>
    <div class="page_summary">
        カードヒーロー＠スマホに投稿された様々なデータを解析し、ランキング形式で記載しています。
    </div>
    <div class="ranking_catalog clearfix">
        <a href="/ranking/finisher/"><div class="zabuton_red">フィニッシャー　ランキング</div></a>
        <a href="/ranking/deck/"><div class="zabuton_blue">デッキ搭載枚数　ランキング</div></a>
    </div>
</div>
